// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleUser      UserRole = "user"
	UserRoleAdmin     UserRole = "admin"
	UserRoleModerator UserRole = "moderator"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerificationTokenType string

const (
	VerificationTokenTypeEmailVerification VerificationTokenType = "email_verification"
	VerificationTokenTypePasswordReset     VerificationTokenType = "password_reset"
)

func (e *VerificationTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationTokenType(s)
	case string:
		*e = VerificationTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationTokenType: %T", src)
	}
	return nil
}

type NullVerificationTokenType struct {
	VerificationTokenType VerificationTokenType `json:"verification_token_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if VerificationTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationTokenType), nil
}

type RefreshToken struct {
	TokenID   uuid.UUID      `json:"token_id"`
	UserID    uuid.UUID      `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
	ExpiresAt time.Time      `json:"expires_at"`
	RevokedAt sql.NullTime   `json:"revoked_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	UserID        uuid.UUID      `json:"user_id"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	PasswordHash  string         `json:"password_hash"`
	FullName      sql.NullString `json:"full_name"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	Role          string         `json:"role"`
	IsBanned      bool           `json:"is_banned"`
	BannedAt      sql.NullTime   `json:"banned_at"`
	BannedReason  sql.NullString `json:"banned_reason"`
	EmailVerified bool           `json:"email_verified"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type VerificationToken struct {
	TokenID   uuid.UUID    `json:"token_id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	Type      string       `json:"type"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}
