// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const banUser = `-- name: BanUser :exec
UPDATE users
SET is_banned     = TRUE,
    banned_at     = now(),
    banned_reason = $2,
    updated_at    = now()
WHERE user_id = $1
`

type BanUserParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	BannedReason sql.NullString `json:"banned_reason"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.ExecContext(ctx, banUser, arg.UserID, arg.BannedReason)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, full_name, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, banned_at, banned_reason, email_verified, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FullName     sql.NullString `json:"full_name"`
	Role         string         `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, banned_at, banned_reason, email_verified, last_login_at, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, banned_at, banned_reason, email_verified, last_login_at, created_at, updated_at FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, banned_at, banned_reason, email_verified, last_login_at, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified = TRUE,
    updated_at     = now()
WHERE user_id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEmailVerified, userID)
	return err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users
SET is_banned     = FALSE,
    banned_at     = NULL,
    banned_reason = NULL,
    updated_at    = now()
WHERE user_id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unbanUser, userID)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = now(),
    updated_at    = now()
WHERE user_id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, userID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2,
    updated_at    = now()
WHERE user_id = $1
`

type UpdatePasswordParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.UserID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name  = COALESCE($1, full_name),
    avatar_url = COALESCE($2, avatar_url),
    updated_at = now()
WHERE user_id = $3
RETURNING user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, banned_at, banned_reason, email_verified, last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	FullName  sql.NullString `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	UserID    uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.FullName, arg.AvatarUrl, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedReason,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
