// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: verification_token.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (user_id, token_hash, type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token_id, user_id, token_hash, type, expires_at, used_at, created_at
`

type CreateVerificationTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	Type      string    `json:"type"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, createVerificationToken,
		arg.UserID,
		arg.TokenHash,
		arg.Type,
		arg.ExpiresAt,
	)
	var i VerificationToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredVerificationTokens = `-- name: DeleteExpiredVerificationTokens :exec
DELETE FROM verification_tokens WHERE user_id = $1 AND expires_at < now()
`

func (q *Queries) DeleteExpiredVerificationTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredVerificationTokens, userID)
	return err
}

const getVerificationTokenByHash = `-- name: GetVerificationTokenByHash :one
SELECT token_id, user_id, token_hash, type, expires_at, used_at, created_at FROM verification_tokens WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetVerificationTokenByHash(ctx context.Context, tokenHash string) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getVerificationTokenByHash, tokenHash)
	var i VerificationToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markVerificationTokenUsed = `-- name: MarkVerificationTokenUsed :exec
UPDATE verification_tokens
SET used_at = now()
WHERE token_hash = $1
`

func (q *Queries) MarkVerificationTokenUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, markVerificationTokenUsed, tokenHash)
	return err
}
