// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: deck_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeckService_ListFolders_FullMethodName          = "/pb.DeckService/ListFolders"
	DeckService_CreateFolder_FullMethodName         = "/pb.DeckService/CreateFolder"
	DeckService_GetFolder_FullMethodName            = "/pb.DeckService/GetFolder"
	DeckService_UpdateFolder_FullMethodName         = "/pb.DeckService/UpdateFolder"
	DeckService_DeleteFolder_FullMethodName         = "/pb.DeckService/DeleteFolder"
	DeckService_AddDeckToFolder_FullMethodName      = "/pb.DeckService/AddDeckToFolder"
	DeckService_RemoveDeckFromFolder_FullMethodName = "/pb.DeckService/RemoveDeckFromFolder"
	DeckService_ListDecks_FullMethodName            = "/pb.DeckService/ListDecks"
	DeckService_CreateDeck_FullMethodName           = "/pb.DeckService/CreateDeck"
	DeckService_ListPublicDecks_FullMethodName      = "/pb.DeckService/ListPublicDecks"
	DeckService_GetDeck_FullMethodName              = "/pb.DeckService/GetDeck"
	DeckService_UpdateDeck_FullMethodName           = "/pb.DeckService/UpdateDeck"
	DeckService_DeleteDeck_FullMethodName           = "/pb.DeckService/DeleteDeck"
	DeckService_UpdateDeckSettings_FullMethodName   = "/pb.DeckService/UpdateDeckSettings"
	DeckService_UpdateDeckVisibility_FullMethodName = "/pb.DeckService/UpdateDeckVisibility"
	DeckService_CloneDeck_FullMethodName            = "/pb.DeckService/CloneDeck"
	DeckService_GetDeckStats_FullMethodName         = "/pb.DeckService/GetDeckStats"
	DeckService_ListDeckCards_FullMethodName        = "/pb.DeckService/ListDeckCards"
	DeckService_CreateCard_FullMethodName           = "/pb.DeckService/CreateCard"
	DeckService_BulkCreateCards_FullMethodName      = "/pb.DeckService/BulkCreateCards"
	DeckService_GetCard_FullMethodName              = "/pb.DeckService/GetCard"
	DeckService_UpdateCard_FullMethodName           = "/pb.DeckService/UpdateCard"
	DeckService_DeleteCard_FullMethodName           = "/pb.DeckService/DeleteCard"
)

// DeckServiceClient is the client API for DeckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeckServiceClient interface {
	// Folders
	ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*ListFoldersResponse, error)
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error)
	GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*GetFolderResponse, error)
	UpdateFolder(ctx context.Context, in *UpdateFolderRequest, opts ...grpc.CallOption) (*UpdateFolderResponse, error)
	DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error)
	AddDeckToFolder(ctx context.Context, in *AddDeckToFolderRequest, opts ...grpc.CallOption) (*AddDeckToFolderResponse, error)
	RemoveDeckFromFolder(ctx context.Context, in *RemoveDeckFromFolderRequest, opts ...grpc.CallOption) (*RemoveDeckFromFolderResponse, error)
	// Decks
	ListDecks(ctx context.Context, in *ListDecksRequest, opts ...grpc.CallOption) (*ListDecksResponse, error)
	CreateDeck(ctx context.Context, in *CreateDeckRequest, opts ...grpc.CallOption) (*CreateDeckResponse, error)
	ListPublicDecks(ctx context.Context, in *ListPublicDecksRequest, opts ...grpc.CallOption) (*ListPublicDecksResponse, error)
	GetDeck(ctx context.Context, in *GetDeckRequest, opts ...grpc.CallOption) (*GetDeckResponse, error)
	UpdateDeck(ctx context.Context, in *UpdateDeckRequest, opts ...grpc.CallOption) (*UpdateDeckResponse, error)
	DeleteDeck(ctx context.Context, in *DeleteDeckRequest, opts ...grpc.CallOption) (*DeleteDeckResponse, error)
	UpdateDeckSettings(ctx context.Context, in *UpdateDeckSettingsRequest, opts ...grpc.CallOption) (*UpdateDeckSettingsResponse, error)
	UpdateDeckVisibility(ctx context.Context, in *UpdateDeckVisibilityRequest, opts ...grpc.CallOption) (*UpdateDeckVisibilityResponse, error)
	CloneDeck(ctx context.Context, in *CloneDeckRequest, opts ...grpc.CallOption) (*CloneDeckResponse, error)
	GetDeckStats(ctx context.Context, in *GetDeckStatsRequest, opts ...grpc.CallOption) (*GetDeckStatsResponse, error)
	ListDeckCards(ctx context.Context, in *ListDeckCardsRequest, opts ...grpc.CallOption) (*ListDeckCardsResponse, error)
	CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardResponse, error)
	BulkCreateCards(ctx context.Context, in *BulkCreateCardsRequest, opts ...grpc.CallOption) (*BulkCreateCardsResponse, error)
	// Cards
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error)
	UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*UpdateCardResponse, error)
	DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...grpc.CallOption) (*DeleteCardResponse, error)
}

type deckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeckServiceClient(cc grpc.ClientConnInterface) DeckServiceClient {
	return &deckServiceClient{cc}
}

func (c *deckServiceClient) ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*ListFoldersResponse, error) {
	out := new(ListFoldersResponse)
	err := c.cc.Invoke(ctx, DeckService_ListFolders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error) {
	out := new(CreateFolderResponse)
	err := c.cc.Invoke(ctx, DeckService_CreateFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*GetFolderResponse, error) {
	out := new(GetFolderResponse)
	err := c.cc.Invoke(ctx, DeckService_GetFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) UpdateFolder(ctx context.Context, in *UpdateFolderRequest, opts ...grpc.CallOption) (*UpdateFolderResponse, error) {
	out := new(UpdateFolderResponse)
	err := c.cc.Invoke(ctx, DeckService_UpdateFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error) {
	out := new(DeleteFolderResponse)
	err := c.cc.Invoke(ctx, DeckService_DeleteFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) AddDeckToFolder(ctx context.Context, in *AddDeckToFolderRequest, opts ...grpc.CallOption) (*AddDeckToFolderResponse, error) {
	out := new(AddDeckToFolderResponse)
	err := c.cc.Invoke(ctx, DeckService_AddDeckToFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) RemoveDeckFromFolder(ctx context.Context, in *RemoveDeckFromFolderRequest, opts ...grpc.CallOption) (*RemoveDeckFromFolderResponse, error) {
	out := new(RemoveDeckFromFolderResponse)
	err := c.cc.Invoke(ctx, DeckService_RemoveDeckFromFolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) ListDecks(ctx context.Context, in *ListDecksRequest, opts ...grpc.CallOption) (*ListDecksResponse, error) {
	out := new(ListDecksResponse)
	err := c.cc.Invoke(ctx, DeckService_ListDecks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) CreateDeck(ctx context.Context, in *CreateDeckRequest, opts ...grpc.CallOption) (*CreateDeckResponse, error) {
	out := new(CreateDeckResponse)
	err := c.cc.Invoke(ctx, DeckService_CreateDeck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) ListPublicDecks(ctx context.Context, in *ListPublicDecksRequest, opts ...grpc.CallOption) (*ListPublicDecksResponse, error) {
	out := new(ListPublicDecksResponse)
	err := c.cc.Invoke(ctx, DeckService_ListPublicDecks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) GetDeck(ctx context.Context, in *GetDeckRequest, opts ...grpc.CallOption) (*GetDeckResponse, error) {
	out := new(GetDeckResponse)
	err := c.cc.Invoke(ctx, DeckService_GetDeck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) UpdateDeck(ctx context.Context, in *UpdateDeckRequest, opts ...grpc.CallOption) (*UpdateDeckResponse, error) {
	out := new(UpdateDeckResponse)
	err := c.cc.Invoke(ctx, DeckService_UpdateDeck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) DeleteDeck(ctx context.Context, in *DeleteDeckRequest, opts ...grpc.CallOption) (*DeleteDeckResponse, error) {
	out := new(DeleteDeckResponse)
	err := c.cc.Invoke(ctx, DeckService_DeleteDeck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) UpdateDeckSettings(ctx context.Context, in *UpdateDeckSettingsRequest, opts ...grpc.CallOption) (*UpdateDeckSettingsResponse, error) {
	out := new(UpdateDeckSettingsResponse)
	err := c.cc.Invoke(ctx, DeckService_UpdateDeckSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) UpdateDeckVisibility(ctx context.Context, in *UpdateDeckVisibilityRequest, opts ...grpc.CallOption) (*UpdateDeckVisibilityResponse, error) {
	out := new(UpdateDeckVisibilityResponse)
	err := c.cc.Invoke(ctx, DeckService_UpdateDeckVisibility_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) CloneDeck(ctx context.Context, in *CloneDeckRequest, opts ...grpc.CallOption) (*CloneDeckResponse, error) {
	out := new(CloneDeckResponse)
	err := c.cc.Invoke(ctx, DeckService_CloneDeck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) GetDeckStats(ctx context.Context, in *GetDeckStatsRequest, opts ...grpc.CallOption) (*GetDeckStatsResponse, error) {
	out := new(GetDeckStatsResponse)
	err := c.cc.Invoke(ctx, DeckService_GetDeckStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) ListDeckCards(ctx context.Context, in *ListDeckCardsRequest, opts ...grpc.CallOption) (*ListDeckCardsResponse, error) {
	out := new(ListDeckCardsResponse)
	err := c.cc.Invoke(ctx, DeckService_ListDeckCards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardResponse, error) {
	out := new(CreateCardResponse)
	err := c.cc.Invoke(ctx, DeckService_CreateCard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) BulkCreateCards(ctx context.Context, in *BulkCreateCardsRequest, opts ...grpc.CallOption) (*BulkCreateCardsResponse, error) {
	out := new(BulkCreateCardsResponse)
	err := c.cc.Invoke(ctx, DeckService_BulkCreateCards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error) {
	out := new(GetCardResponse)
	err := c.cc.Invoke(ctx, DeckService_GetCard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*UpdateCardResponse, error) {
	out := new(UpdateCardResponse)
	err := c.cc.Invoke(ctx, DeckService_UpdateCard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...grpc.CallOption) (*DeleteCardResponse, error) {
	out := new(DeleteCardResponse)
	err := c.cc.Invoke(ctx, DeckService_DeleteCard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeckServiceServer is the server API for DeckService service.
// All implementations must embed UnimplementedDeckServiceServer
// for forward compatibility
type DeckServiceServer interface {
	// Folders
	ListFolders(context.Context, *ListFoldersRequest) (*ListFoldersResponse, error)
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error)
	GetFolder(context.Context, *GetFolderRequest) (*GetFolderResponse, error)
	UpdateFolder(context.Context, *UpdateFolderRequest) (*UpdateFolderResponse, error)
	DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error)
	AddDeckToFolder(context.Context, *AddDeckToFolderRequest) (*AddDeckToFolderResponse, error)
	RemoveDeckFromFolder(context.Context, *RemoveDeckFromFolderRequest) (*RemoveDeckFromFolderResponse, error)
	// Decks
	ListDecks(context.Context, *ListDecksRequest) (*ListDecksResponse, error)
	CreateDeck(context.Context, *CreateDeckRequest) (*CreateDeckResponse, error)
	ListPublicDecks(context.Context, *ListPublicDecksRequest) (*ListPublicDecksResponse, error)
	GetDeck(context.Context, *GetDeckRequest) (*GetDeckResponse, error)
	UpdateDeck(context.Context, *UpdateDeckRequest) (*UpdateDeckResponse, error)
	DeleteDeck(context.Context, *DeleteDeckRequest) (*DeleteDeckResponse, error)
	UpdateDeckSettings(context.Context, *UpdateDeckSettingsRequest) (*UpdateDeckSettingsResponse, error)
	UpdateDeckVisibility(context.Context, *UpdateDeckVisibilityRequest) (*UpdateDeckVisibilityResponse, error)
	CloneDeck(context.Context, *CloneDeckRequest) (*CloneDeckResponse, error)
	GetDeckStats(context.Context, *GetDeckStatsRequest) (*GetDeckStatsResponse, error)
	ListDeckCards(context.Context, *ListDeckCardsRequest) (*ListDeckCardsResponse, error)
	CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error)
	BulkCreateCards(context.Context, *BulkCreateCardsRequest) (*BulkCreateCardsResponse, error)
	// Cards
	GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error)
	UpdateCard(context.Context, *UpdateCardRequest) (*UpdateCardResponse, error)
	DeleteCard(context.Context, *DeleteCardRequest) (*DeleteCardResponse, error)
	mustEmbedUnimplementedDeckServiceServer()
}

// UnimplementedDeckServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeckServiceServer struct {
}

func (UnimplementedDeckServiceServer) ListFolders(context.Context, *ListFoldersRequest) (*ListFoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFolders not implemented")
}
func (UnimplementedDeckServiceServer) CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedDeckServiceServer) GetFolder(context.Context, *GetFolderRequest) (*GetFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFolder not implemented")
}
func (UnimplementedDeckServiceServer) UpdateFolder(context.Context, *UpdateFolderRequest) (*UpdateFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFolder not implemented")
}
func (UnimplementedDeckServiceServer) DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFolder not implemented")
}
func (UnimplementedDeckServiceServer) AddDeckToFolder(context.Context, *AddDeckToFolderRequest) (*AddDeckToFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDeckToFolder not implemented")
}
func (UnimplementedDeckServiceServer) RemoveDeckFromFolder(context.Context, *RemoveDeckFromFolderRequest) (*RemoveDeckFromFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDeckFromFolder not implemented")
}
func (UnimplementedDeckServiceServer) ListDecks(context.Context, *ListDecksRequest) (*ListDecksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDecks not implemented")
}
func (UnimplementedDeckServiceServer) CreateDeck(context.Context, *CreateDeckRequest) (*CreateDeckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeck not implemented")
}
func (UnimplementedDeckServiceServer) ListPublicDecks(context.Context, *ListPublicDecksRequest) (*ListPublicDecksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublicDecks not implemented")
}
func (UnimplementedDeckServiceServer) GetDeck(context.Context, *GetDeckRequest) (*GetDeckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeck not implemented")
}
func (UnimplementedDeckServiceServer) UpdateDeck(context.Context, *UpdateDeckRequest) (*UpdateDeckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeck not implemented")
}
func (UnimplementedDeckServiceServer) DeleteDeck(context.Context, *DeleteDeckRequest) (*DeleteDeckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeck not implemented")
}
func (UnimplementedDeckServiceServer) UpdateDeckSettings(context.Context, *UpdateDeckSettingsRequest) (*UpdateDeckSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeckSettings not implemented")
}
func (UnimplementedDeckServiceServer) UpdateDeckVisibility(context.Context, *UpdateDeckVisibilityRequest) (*UpdateDeckVisibilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeckVisibility not implemented")
}
func (UnimplementedDeckServiceServer) CloneDeck(context.Context, *CloneDeckRequest) (*CloneDeckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneDeck not implemented")
}
func (UnimplementedDeckServiceServer) GetDeckStats(context.Context, *GetDeckStatsRequest) (*GetDeckStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeckStats not implemented")
}
func (UnimplementedDeckServiceServer) ListDeckCards(context.Context, *ListDeckCardsRequest) (*ListDeckCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeckCards not implemented")
}
func (UnimplementedDeckServiceServer) CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCard not implemented")
}
func (UnimplementedDeckServiceServer) BulkCreateCards(context.Context, *BulkCreateCardsRequest) (*BulkCreateCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkCreateCards not implemented")
}
func (UnimplementedDeckServiceServer) GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedDeckServiceServer) UpdateCard(context.Context, *UpdateCardRequest) (*UpdateCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCard not implemented")
}
func (UnimplementedDeckServiceServer) DeleteCard(context.Context, *DeleteCardRequest) (*DeleteCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCard not implemented")
}
func (UnimplementedDeckServiceServer) mustEmbedUnimplementedDeckServiceServer() {}

// UnsafeDeckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeckServiceServer will
// result in compilation errors.
type UnsafeDeckServiceServer interface {
	mustEmbedUnimplementedDeckServiceServer()
}

func RegisterDeckServiceServer(s grpc.ServiceRegistrar, srv DeckServiceServer) {
	s.RegisterService(&DeckService_ServiceDesc, srv)
}

func _DeckService_ListFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).ListFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_ListFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).ListFolders(ctx, req.(*ListFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_GetFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).GetFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_GetFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).GetFolder(ctx, req.(*GetFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_UpdateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).UpdateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_UpdateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).UpdateFolder(ctx, req.(*UpdateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_DeleteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).DeleteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_DeleteFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).DeleteFolder(ctx, req.(*DeleteFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_AddDeckToFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeckToFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).AddDeckToFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_AddDeckToFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).AddDeckToFolder(ctx, req.(*AddDeckToFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_RemoveDeckFromFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeckFromFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).RemoveDeckFromFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_RemoveDeckFromFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).RemoveDeckFromFolder(ctx, req.(*RemoveDeckFromFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_ListDecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).ListDecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_ListDecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).ListDecks(ctx, req.(*ListDecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_CreateDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).CreateDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_CreateDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).CreateDeck(ctx, req.(*CreateDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_ListPublicDecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicDecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).ListPublicDecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_ListPublicDecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).ListPublicDecks(ctx, req.(*ListPublicDecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_GetDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).GetDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_GetDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).GetDeck(ctx, req.(*GetDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_UpdateDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).UpdateDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_UpdateDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).UpdateDeck(ctx, req.(*UpdateDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_DeleteDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).DeleteDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_DeleteDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).DeleteDeck(ctx, req.(*DeleteDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_UpdateDeckSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeckSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).UpdateDeckSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_UpdateDeckSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).UpdateDeckSettings(ctx, req.(*UpdateDeckSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_UpdateDeckVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeckVisibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).UpdateDeckVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_UpdateDeckVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).UpdateDeckVisibility(ctx, req.(*UpdateDeckVisibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_CloneDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).CloneDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_CloneDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).CloneDeck(ctx, req.(*CloneDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_GetDeckStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeckStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).GetDeckStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_GetDeckStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).GetDeckStats(ctx, req.(*GetDeckStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_ListDeckCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeckCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).ListDeckCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_ListDeckCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).ListDeckCards(ctx, req.(*ListDeckCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_CreateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).CreateCard(ctx, req.(*CreateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_BulkCreateCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkCreateCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).BulkCreateCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_BulkCreateCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).BulkCreateCards(ctx, req.(*BulkCreateCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_UpdateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).UpdateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_UpdateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).UpdateCard(ctx, req.(*UpdateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_DeleteCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).DeleteCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_DeleteCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).DeleteCard(ctx, req.(*DeleteCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeckService_ServiceDesc is the grpc.ServiceDesc for DeckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DeckService",
	HandlerType: (*DeckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFolders",
			Handler:    _DeckService_ListFolders_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _DeckService_CreateFolder_Handler,
		},
		{
			MethodName: "GetFolder",
			Handler:    _DeckService_GetFolder_Handler,
		},
		{
			MethodName: "UpdateFolder",
			Handler:    _DeckService_UpdateFolder_Handler,
		},
		{
			MethodName: "DeleteFolder",
			Handler:    _DeckService_DeleteFolder_Handler,
		},
		{
			MethodName: "AddDeckToFolder",
			Handler:    _DeckService_AddDeckToFolder_Handler,
		},
		{
			MethodName: "RemoveDeckFromFolder",
			Handler:    _DeckService_RemoveDeckFromFolder_Handler,
		},
		{
			MethodName: "ListDecks",
			Handler:    _DeckService_ListDecks_Handler,
		},
		{
			MethodName: "CreateDeck",
			Handler:    _DeckService_CreateDeck_Handler,
		},
		{
			MethodName: "ListPublicDecks",
			Handler:    _DeckService_ListPublicDecks_Handler,
		},
		{
			MethodName: "GetDeck",
			Handler:    _DeckService_GetDeck_Handler,
		},
		{
			MethodName: "UpdateDeck",
			Handler:    _DeckService_UpdateDeck_Handler,
		},
		{
			MethodName: "DeleteDeck",
			Handler:    _DeckService_DeleteDeck_Handler,
		},
		{
			MethodName: "UpdateDeckSettings",
			Handler:    _DeckService_UpdateDeckSettings_Handler,
		},
		{
			MethodName: "UpdateDeckVisibility",
			Handler:    _DeckService_UpdateDeckVisibility_Handler,
		},
		{
			MethodName: "CloneDeck",
			Handler:    _DeckService_CloneDeck_Handler,
		},
		{
			MethodName: "GetDeckStats",
			Handler:    _DeckService_GetDeckStats_Handler,
		},
		{
			MethodName: "ListDeckCards",
			Handler:    _DeckService_ListDeckCards_Handler,
		},
		{
			MethodName: "CreateCard",
			Handler:    _DeckService_CreateCard_Handler,
		},
		{
			MethodName: "BulkCreateCards",
			Handler:    _DeckService_BulkCreateCards_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _DeckService_GetCard_Handler,
		},
		{
			MethodName: "UpdateCard",
			Handler:    _DeckService_UpdateCard_Handler,
		},
		{
			MethodName: "DeleteCard",
			Handler:    _DeckService_DeleteCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deck_service.proto",
}
