// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (
  user_id,
  note_id,
  deck_id,
  state,
  next_review_date
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING card_id, user_id, note_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, next_review_date, t_avg, last_review_date, created_at
`

type CreateCardParams struct {
	UserID         uuid.UUID     `json:"user_id"`
	NoteID         uuid.UUID     `json:"note_id"`
	DeckID         uuid.UUID     `json:"deck_id"`
	State          NullCardState `json:"state"`
	NextReviewDate sql.NullTime  `json:"next_review_date"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.UserID,
		arg.NoteID,
		arg.DeckID,
		arg.State,
		arg.NextReviewDate,
	)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.NoteID,
		&i.DeckID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.ScheduledDays,
		&i.NextReviewDate,
		&i.TAvg,
		&i.LastReviewDate,
		&i.CreatedAt,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT card_id, user_id, note_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, next_review_date, t_avg, last_review_date, created_at FROM cards
WHERE card_id = $1 LIMIT 1
`

func (q *Queries) GetCard(ctx context.Context, cardID uuid.UUID) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, cardID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.NoteID,
		&i.DeckID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.ScheduledDays,
		&i.NextReviewDate,
		&i.TAvg,
		&i.LastReviewDate,
		&i.CreatedAt,
	)
	return i, err
}

const listCardsByDeck = `-- name: ListCardsByDeck :many
SELECT card_id, user_id, note_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, next_review_date, t_avg, last_review_date, created_at FROM cards
WHERE deck_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCardsByDeck(ctx context.Context, deckID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.CardID,
			&i.UserID,
			&i.NoteID,
			&i.DeckID,
			&i.State,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.ScheduledDays,
			&i.NextReviewDate,
			&i.TAvg,
			&i.LastReviewDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCardsByDeck = `-- name: ListDueCardsByDeck :many
SELECT card_id, user_id, note_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, next_review_date, t_avg, last_review_date, created_at FROM cards
WHERE deck_id = $1
  AND next_review_date <= NOW()
  AND state != 'new'
ORDER BY next_review_date ASC
LIMIT $2
`

type ListDueCardsByDeckParams struct {
	DeckID uuid.UUID `json:"deck_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListDueCardsByDeck(ctx context.Context, arg ListDueCardsByDeckParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listDueCardsByDeck, arg.DeckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.CardID,
			&i.UserID,
			&i.NoteID,
			&i.DeckID,
			&i.State,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.ScheduledDays,
			&i.NextReviewDate,
			&i.TAvg,
			&i.LastReviewDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardReviewState = `-- name: UpdateCardReviewState :one
UPDATE cards
SET state = $2,
    stability = $3,
    difficulty = $4,
    reps = $5,
    lapses = $6,
    scheduled_days = $7,
    next_review_date = $8,
    t_avg = $9,
    last_review_date = CURRENT_TIMESTAMP
WHERE card_id = $1
RETURNING card_id, user_id, note_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, next_review_date, t_avg, last_review_date, created_at
`

type UpdateCardReviewStateParams struct {
	CardID         uuid.UUID       `json:"card_id"`
	State          NullCardState   `json:"state"`
	Stability      sql.NullFloat64 `json:"stability"`
	Difficulty     sql.NullFloat64 `json:"difficulty"`
	Reps           sql.NullInt32   `json:"reps"`
	Lapses         sql.NullInt32   `json:"lapses"`
	ScheduledDays  sql.NullInt32   `json:"scheduled_days"`
	NextReviewDate sql.NullTime    `json:"next_review_date"`
	TAvg           sql.NullFloat64 `json:"t_avg"`
}

func (q *Queries) UpdateCardReviewState(ctx context.Context, arg UpdateCardReviewStateParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCardReviewState,
		arg.CardID,
		arg.State,
		arg.Stability,
		arg.Difficulty,
		arg.Reps,
		arg.Lapses,
		arg.ScheduledDays,
		arg.NextReviewDate,
		arg.TAvg,
	)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.UserID,
		&i.NoteID,
		&i.DeckID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.ScheduledDays,
		&i.NextReviewDate,
		&i.TAvg,
		&i.LastReviewDate,
		&i.CreatedAt,
	)
	return i, err
}
