// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decks.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (
  user_id,
  name,
  description,
  is_public,
  status,
  settings
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING deck_id, user_id, name, description, is_public, status, settings, created_at, updated_at
`

type CreateDeckParams struct {
	UserID      uuid.UUID             `json:"user_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	IsPublic    sql.NullBool          `json:"is_public"`
	Status      NullContentStatus     `json:"status"`
	Settings    pqtype.NullRawMessage `json:"settings"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.Status,
		arg.Settings,
	)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :one
DELETE FROM decks
WHERE deck_id = $1
RETURNING deck_id, user_id, name, description, is_public, status, settings, created_at, updated_at
`

func (q *Queries) DeleteDeck(ctx context.Context, deckID uuid.UUID) (Deck, error) {
	row := q.db.QueryRowContext(ctx, deleteDeck, deckID)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeck = `-- name: GetDeck :one
SELECT deck_id, user_id, name, description, is_public, status, settings, created_at, updated_at FROM decks
WHERE deck_id = $1 LIMIT 1
`

func (q *Queries) GetDeck(ctx context.Context, deckID uuid.UUID) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeck, deckID)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicActiveDecks = `-- name: ListPublicActiveDecks :many
SELECT deck_id, user_id, name, description, is_public, status, settings, created_at, updated_at FROM decks
WHERE is_public = true
  AND status = 'active'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicActiveDecksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicActiveDecks(ctx context.Context, arg ListPublicActiveDecksParams) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listPublicActiveDecks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.DeckID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDecks = `-- name: ListUserDecks :many
SELECT deck_id, user_id, name, description, is_public, status, settings, created_at, updated_at FROM decks
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserDecksParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserDecks(ctx context.Context, arg ListUserDecksParams) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listUserDecks, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.DeckID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublicDecks = `-- name: SearchPublicDecks :many
SELECT deck_id, user_id, name, description, is_public, status, settings, created_at, updated_at FROM decks
WHERE is_public = true
  AND status = 'active'
  AND (
    name ILIKE '%' || $1 || '%'
    OR COALESCE(description, '') ILIKE '%' || $1 || '%'
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchPublicDecksParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchPublicDecks(ctx context.Context, arg SearchPublicDecksParams) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, searchPublicDecks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.DeckID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE decks
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    is_public = COALESCE($3, is_public),
    status = COALESCE($4, status),
    settings = COALESCE($5, settings),
    updated_at = CURRENT_TIMESTAMP
WHERE deck_id = $6
RETURNING deck_id, user_id, name, description, is_public, status, settings, created_at, updated_at
`

type UpdateDeckParams struct {
	Name        sql.NullString        `json:"name"`
	Description sql.NullString        `json:"description"`
	IsPublic    sql.NullBool          `json:"is_public"`
	Status      NullContentStatus     `json:"status"`
	Settings    pqtype.NullRawMessage `json:"settings"`
	DeckID      uuid.UUID             `json:"deck_id"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, updateDeck,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.Status,
		arg.Settings,
		arg.DeckID,
	)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
