// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addDeckToFolder = `-- name: AddDeckToFolder :one
INSERT INTO folder_decks (
  folder_id,
  deck_id
) VALUES (
  $1, $2
)
ON CONFLICT (folder_id, deck_id) DO NOTHING
RETURNING folder_id, deck_id
`

type AddDeckToFolderParams struct {
	FolderID uuid.UUID `json:"folder_id"`
	DeckID   uuid.UUID `json:"deck_id"`
}

func (q *Queries) AddDeckToFolder(ctx context.Context, arg AddDeckToFolderParams) (FolderDeck, error) {
	row := q.db.QueryRowContext(ctx, addDeckToFolder, arg.FolderID, arg.DeckID)
	var i FolderDeck
	err := row.Scan(&i.FolderID, &i.DeckID)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
  user_id,
  name,
  description
) VALUES (
  $1, $2, $3
)
RETURNING folder_id, user_id, name, description, created_at
`

type CreateFolderParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, arg.UserID, arg.Name, arg.Description)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getFolder = `-- name: GetFolder :one
SELECT folder_id, user_id, name, description, created_at FROM folders
WHERE folder_id = $1 LIMIT 1
`

func (q *Queries) GetFolder(ctx context.Context, folderID uuid.UUID) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, folderID)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listDecksInFolder = `-- name: ListDecksInFolder :many
SELECT d.deck_id, d.user_id, d.name, d.description, d.is_public, d.status, d.settings, d.created_at, d.updated_at
FROM folder_decks fd
JOIN decks d ON d.deck_id = fd.deck_id
WHERE fd.folder_id = $1
ORDER BY d.created_at DESC
`

func (q *Queries) ListDecksInFolder(ctx context.Context, folderID uuid.UUID) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listDecksInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.DeckID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByUser = `-- name: ListFoldersByUser :many
SELECT folder_id, user_id, name, description, created_at FROM folders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFoldersByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListFoldersByUser(ctx context.Context, arg ListFoldersByUserParams) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.FolderID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDeckFromFolder = `-- name: RemoveDeckFromFolder :exec
DELETE FROM folder_decks
WHERE folder_id = $1
  AND deck_id = $2
`

type RemoveDeckFromFolderParams struct {
	FolderID uuid.UUID `json:"folder_id"`
	DeckID   uuid.UUID `json:"deck_id"`
}

func (q *Queries) RemoveDeckFromFolder(ctx context.Context, arg RemoveDeckFromFolderParams) error {
	_, err := q.db.ExecContext(ctx, removeDeckFromFolder, arg.FolderID, arg.DeckID)
	return err
}
