// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type CardState string

const (
	CardStateNew        CardState = "new"
	CardStateLearning   CardState = "learning"
	CardStateReview     CardState = "review"
	CardStateRelearning CardState = "relearning"
)

func (e *CardState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardState(s)
	case string:
		*e = CardState(s)
	default:
		return fmt.Errorf("unsupported scan type for CardState: %T", src)
	}
	return nil
}

type NullCardState struct {
	CardState CardState `json:"card_state"`
	Valid     bool      `json:"valid"` // Valid is true if CardState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardState) Scan(value interface{}) error {
	if value == nil {
		ns.CardState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardState), nil
}

type ContentStatus string

const (
	ContentStatusActive         ContentStatus = "active"
	ContentStatusHidden         ContentStatus = "hidden"
	ContentStatusDeletedByAdmin ContentStatus = "deleted_by_admin"
)

func (e *ContentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentStatus(s)
	case string:
		*e = ContentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentStatus: %T", src)
	}
	return nil
}

type NullContentStatus struct {
	ContentStatus ContentStatus `json:"content_status"`
	Valid         bool          `json:"valid"` // Valid is true if ContentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentStatus), nil
}

type ReportTarget string

const (
	ReportTargetDeck ReportTarget = "deck"
	ReportTargetUser ReportTarget = "user"
)

func (e *ReportTarget) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportTarget(s)
	case string:
		*e = ReportTarget(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportTarget: %T", src)
	}
	return nil
}

type NullReportTarget struct {
	ReportTarget ReportTarget `json:"report_target"`
	Valid        bool         `json:"valid"` // Valid is true if ReportTarget is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportTarget) Scan(value interface{}) error {
	if value == nil {
		ns.ReportTarget, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportTarget.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportTarget) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportTarget), nil
}

type UserRole string

const (
	UserRoleUser      UserRole = "user"
	UserRoleAdmin     UserRole = "admin"
	UserRoleModerator UserRole = "moderator"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Card struct {
	CardID         uuid.UUID       `json:"card_id"`
	UserID         uuid.UUID       `json:"user_id"`
	NoteID         uuid.UUID       `json:"note_id"`
	DeckID         uuid.UUID       `json:"deck_id"`
	State          NullCardState   `json:"state"`
	Stability      sql.NullFloat64 `json:"stability"`
	Difficulty     sql.NullFloat64 `json:"difficulty"`
	Reps           sql.NullInt32   `json:"reps"`
	Lapses         sql.NullInt32   `json:"lapses"`
	ScheduledDays  sql.NullInt32   `json:"scheduled_days"`
	NextReviewDate sql.NullTime    `json:"next_review_date"`
	TAvg           sql.NullFloat64 `json:"t_avg"`
	LastReviewDate sql.NullTime    `json:"last_review_date"`
	CreatedAt      sql.NullTime    `json:"created_at"`
}

type Deck struct {
	DeckID      uuid.UUID             `json:"deck_id"`
	UserID      uuid.UUID             `json:"user_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	IsPublic    sql.NullBool          `json:"is_public"`
	Status      NullContentStatus     `json:"status"`
	Settings    pqtype.NullRawMessage `json:"settings"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type Folder struct {
	FolderID    uuid.UUID      `json:"folder_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type FolderDeck struct {
	FolderID uuid.UUID `json:"folder_id"`
	DeckID   uuid.UUID `json:"deck_id"`
}

type Note struct {
	NoteID       uuid.UUID      `json:"note_id"`
	UserID       uuid.UUID      `json:"user_id"`
	ContentFront string         `json:"content_front"`
	ContentBack  string         `json:"content_back"`
	ImageUrl     sql.NullString `json:"image_url"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Report struct {
	ReportID       uuid.UUID      `json:"report_id"`
	ReporterID     uuid.UUID      `json:"reporter_id"`
	TargetType     ReportTarget   `json:"target_type"`
	TargetID       uuid.UUID      `json:"target_id"`
	ReasonCategory sql.NullString `json:"reason_category"`
	Description    sql.NullString `json:"description"`
	Status         sql.NullString `json:"status"`
	AdminNote      sql.NullString `json:"admin_note"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	ResolvedAt     sql.NullTime   `json:"resolved_at"`
}

type Revlog struct {
	LogID            uuid.UUID       `json:"log_id"`
	CardID           uuid.UUID       `json:"card_id"`
	UserID           uuid.UUID       `json:"user_id"`
	Rating           int16           `json:"rating"`
	DurationMs       int32           `json:"duration_ms"`
	State            CardState       `json:"state"`
	ElapsedDays      int32           `json:"elapsed_days"`
	StabilityBefore  sql.NullFloat64 `json:"stability_before"`
	DifficultyBefore sql.NullFloat64 `json:"difficulty_before"`
	ReviewTime       sql.NullTime    `json:"review_time"`
}

type SessionCard struct {
	SessionID uuid.UUID     `json:"session_id"`
	CardID    uuid.NullUUID `json:"card_id"`
	Position  int32         `json:"position"`
}

type StudySession struct {
	SessionID          uuid.UUID      `json:"session_id"`
	UserID             uuid.UUID      `json:"user_id"`
	DeckID             uuid.UUID      `json:"deck_id"`
	Status             sql.NullString `json:"status"`
	LastCompletedIndex sql.NullInt32  `json:"last_completed_index"`
	LastAccessedAt     sql.NullTime   `json:"last_accessed_at"`
}

type User struct {
	UserID        uuid.UUID      `json:"user_id"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	PasswordHash  string         `json:"password_hash"`
	FullName      sql.NullString `json:"full_name"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	Role          NullUserRole   `json:"role"`
	IsBanned      sql.NullBool   `json:"is_banned"`
	StreakCount   sql.NullInt32  `json:"streak_count"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	LastLogin     sql.NullTime   `json:"last_login"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type UserFsrsWeight struct {
	UserID    uuid.UUID    `json:"user_id"`
	Version   int32        `json:"version"`
	Weights   []float64    `json:"weights"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
