// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
  user_id,
  content_front,
  content_back,
  image_url
) VALUES (
  $1, $2, $3, $4
)
RETURNING note_id, user_id, content_front, content_back, image_url, created_at
`

type CreateNoteParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	ContentFront string         `json:"content_front"`
	ContentBack  string         `json:"content_back"`
	ImageUrl     sql.NullString `json:"image_url"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.UserID,
		arg.ContentFront,
		arg.ContentBack,
		arg.ImageUrl,
	)
	var i Note
	err := row.Scan(
		&i.NoteID,
		&i.UserID,
		&i.ContentFront,
		&i.ContentBack,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT note_id, user_id, content_front, content_back, image_url, created_at FROM notes
WHERE note_id = $1 LIMIT 1
`

func (q *Queries) GetNote(ctx context.Context, noteID uuid.UUID) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, noteID)
	var i Note
	err := row.Scan(
		&i.NoteID,
		&i.UserID,
		&i.ContentFront,
		&i.ContentBack,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}
