// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddDeckToFolder(ctx context.Context, arg AddDeckToFolderParams) (FolderDeck, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateRevlog(ctx context.Context, arg CreateRevlogParams) (Revlog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDeck(ctx context.Context, deckID uuid.UUID) (Deck, error)
	GetCard(ctx context.Context, cardID uuid.UUID) (Card, error)
	GetDeck(ctx context.Context, deckID uuid.UUID) (Deck, error)
	GetFolder(ctx context.Context, folderID uuid.UUID) (Folder, error)
	GetNote(ctx context.Context, noteID uuid.UUID) (Note, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (User, error)
	ListCardsByDeck(ctx context.Context, deckID uuid.UUID) ([]Card, error)
	ListDecksInFolder(ctx context.Context, folderID uuid.UUID) ([]Deck, error)
	ListDueCardsByDeck(ctx context.Context, arg ListDueCardsByDeckParams) ([]Card, error)
	ListFoldersByUser(ctx context.Context, arg ListFoldersByUserParams) ([]Folder, error)
	ListPublicActiveDecks(ctx context.Context, arg ListPublicActiveDecksParams) ([]Deck, error)
	ListRevlogsByCard(ctx context.Context, arg ListRevlogsByCardParams) ([]Revlog, error)
	ListRevlogsByUser(ctx context.Context, arg ListRevlogsByUserParams) ([]Revlog, error)
	ListUserDecks(ctx context.Context, arg ListUserDecksParams) ([]Deck, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveDeckFromFolder(ctx context.Context, arg RemoveDeckFromFolderParams) error
	SearchPublicDecks(ctx context.Context, arg SearchPublicDecksParams) ([]Deck, error)
	UpdateCardReviewState(ctx context.Context, arg UpdateCardReviewStateParams) (Card, error)
	UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
