// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revlogs.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRevlog = `-- name: CreateRevlog :one
INSERT INTO revlogs (
  card_id,
  user_id,
  rating,
  duration_ms,
  state,
  elapsed_days,
  stability_before,
  difficulty_before
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING log_id, card_id, user_id, rating, duration_ms, state, elapsed_days, stability_before, difficulty_before, review_time
`

type CreateRevlogParams struct {
	CardID           uuid.UUID       `json:"card_id"`
	UserID           uuid.UUID       `json:"user_id"`
	Rating           int16           `json:"rating"`
	DurationMs       int32           `json:"duration_ms"`
	State            CardState       `json:"state"`
	ElapsedDays      int32           `json:"elapsed_days"`
	StabilityBefore  sql.NullFloat64 `json:"stability_before"`
	DifficultyBefore sql.NullFloat64 `json:"difficulty_before"`
}

func (q *Queries) CreateRevlog(ctx context.Context, arg CreateRevlogParams) (Revlog, error) {
	row := q.db.QueryRowContext(ctx, createRevlog,
		arg.CardID,
		arg.UserID,
		arg.Rating,
		arg.DurationMs,
		arg.State,
		arg.ElapsedDays,
		arg.StabilityBefore,
		arg.DifficultyBefore,
	)
	var i Revlog
	err := row.Scan(
		&i.LogID,
		&i.CardID,
		&i.UserID,
		&i.Rating,
		&i.DurationMs,
		&i.State,
		&i.ElapsedDays,
		&i.StabilityBefore,
		&i.DifficultyBefore,
		&i.ReviewTime,
	)
	return i, err
}

const listRevlogsByCard = `-- name: ListRevlogsByCard :many
SELECT log_id, card_id, user_id, rating, duration_ms, state, elapsed_days, stability_before, difficulty_before, review_time FROM revlogs
WHERE card_id = $1
ORDER BY review_time DESC
LIMIT $2 OFFSET $3
`

type ListRevlogsByCardParams struct {
	CardID uuid.UUID `json:"card_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListRevlogsByCard(ctx context.Context, arg ListRevlogsByCardParams) ([]Revlog, error) {
	rows, err := q.db.QueryContext(ctx, listRevlogsByCard, arg.CardID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Revlog{}
	for rows.Next() {
		var i Revlog
		if err := rows.Scan(
			&i.LogID,
			&i.CardID,
			&i.UserID,
			&i.Rating,
			&i.DurationMs,
			&i.State,
			&i.ElapsedDays,
			&i.StabilityBefore,
			&i.DifficultyBefore,
			&i.ReviewTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevlogsByUser = `-- name: ListRevlogsByUser :many
SELECT log_id, card_id, user_id, rating, duration_ms, state, elapsed_days, stability_before, difficulty_before, review_time FROM revlogs
WHERE user_id = $1
ORDER BY review_time DESC
LIMIT $2 OFFSET $3
`

type ListRevlogsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListRevlogsByUser(ctx context.Context, arg ListRevlogsByUserParams) ([]Revlog, error) {
	rows, err := q.db.QueryContext(ctx, listRevlogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Revlog{}
	for rows.Next() {
		var i Revlog
		if err := rows.Scan(
			&i.LogID,
			&i.CardID,
			&i.UserID,
			&i.Rating,
			&i.DurationMs,
			&i.State,
			&i.ElapsedDays,
			&i.StabilityBefore,
			&i.DifficultyBefore,
			&i.ReviewTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
