// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  email,
  password_hash,
  full_name,
  avatar_url,
  role
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, streak_count, email_verified, last_login, created_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FullName     sql.NullString `json:"full_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	Role         NullUserRole   `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.AvatarUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.StreakCount,
		&i.EmailVerified,
		&i.LastLogin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, streak_count, email_verified, last_login, created_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.StreakCount,
		&i.EmailVerified,
		&i.LastLogin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, streak_count, email_verified, last_login, created_at FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.StreakCount,
		&i.EmailVerified,
		&i.LastLogin,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, streak_count, email_verified, last_login, created_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.Role,
			&i.IsBanned,
			&i.StreakCount,
			&i.EmailVerified,
			&i.LastLogin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name = COALESCE($1, full_name),
    avatar_url = COALESCE($2, avatar_url),
    last_login = COALESCE($3, last_login)
WHERE user_id = $4
RETURNING user_id, username, email, password_hash, full_name, avatar_url, role, is_banned, streak_count, email_verified, last_login, created_at
`

type UpdateUserProfileParams struct {
	FullName  sql.NullString `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	LastLogin sql.NullTime   `json:"last_login"`
	UserID    uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.FullName,
		arg.AvatarUrl,
		arg.LastLogin,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.StreakCount,
		&i.EmailVerified,
		&i.LastLogin,
		&i.CreatedAt,
	)
	return i, err
}
