// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: deck.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const cloneDeck = `-- name: CloneDeck :one
INSERT INTO decks (user_id, name, description, is_public, cloned_from)
VALUES ($1, $2, $3, FALSE, $4)
RETURNING deck_id, user_id, name, description, is_public, status, settings, card_count, cloned_from, created_at, updated_at
`

type CloneDeckParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ClonedFrom  uuid.NullUUID  `json:"cloned_from"`
}

func (q *Queries) CloneDeck(ctx context.Context, arg CloneDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, cloneDeck,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ClonedFrom,
	)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CardCount,
		&i.ClonedFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countDecksByUser = `-- name: CountDecksByUser :one
SELECT COUNT(*) FROM decks WHERE user_id = $1 AND status != 'deleted'
`

func (q *Queries) CountDecksByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDecksByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicDecks = `-- name: CountPublicDecks :one
SELECT COUNT(*) FROM decks WHERE is_public = TRUE AND status = 'active'
`

func (q *Queries) CountPublicDecks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicDecks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (user_id, name, description, is_public)
VALUES ($1, $2, $3, $4)
RETURNING deck_id, user_id, name, description, is_public, status, settings, card_count, cloned_from, created_at, updated_at
`

type CreateDeckParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsPublic    bool           `json:"is_public"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CardCount,
		&i.ClonedFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementCardCount = `-- name: DecrementCardCount :exec
UPDATE decks SET card_count = GREATEST(card_count - 1, 0), updated_at = now() WHERE deck_id = $1
`

func (q *Queries) DecrementCardCount(ctx context.Context, deckID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementCardCount, deckID)
	return err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT deck_id, user_id, name, description, is_public, status, settings, card_count, cloned_from, created_at, updated_at FROM decks WHERE deck_id = $1 LIMIT 1
`

func (q *Queries) GetDeckByID(ctx context.Context, deckID uuid.UUID) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeckByID, deckID)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CardCount,
		&i.ClonedFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCardCount = `-- name: IncrementCardCount :exec
UPDATE decks SET card_count = card_count + 1, updated_at = now() WHERE deck_id = $1
`

func (q *Queries) IncrementCardCount(ctx context.Context, deckID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementCardCount, deckID)
	return err
}

const listDecksByUser = `-- name: ListDecksByUser :many
SELECT deck_id, user_id, name, description, is_public, status, settings, card_count, cloned_from, created_at, updated_at FROM decks
WHERE user_id = $1 AND status != 'deleted'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDecksByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListDecksByUser(ctx context.Context, arg ListDecksByUserParams) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listDecksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.DeckID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Status,
			&i.Settings,
			&i.CardCount,
			&i.ClonedFrom,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicDecks = `-- name: ListPublicDecks :many
SELECT deck_id, user_id, name, description, is_public, status, settings, card_count, cloned_from, created_at, updated_at FROM decks
WHERE is_public = TRUE AND status = 'active'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicDecksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicDecks(ctx context.Context, arg ListPublicDecksParams) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listPublicDecks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.DeckID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Status,
			&i.Settings,
			&i.CardCount,
			&i.ClonedFrom,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDeck = `-- name: SoftDeleteDeck :exec
UPDATE decks
SET status     = 'deleted',
    updated_at = now()
WHERE deck_id = $1 AND user_id = $2
`

type SoftDeleteDeckParams struct {
	DeckID uuid.UUID `json:"deck_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteDeck(ctx context.Context, arg SoftDeleteDeckParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDeck, arg.DeckID, arg.UserID)
	return err
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE decks
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at  = now()
WHERE deck_id = $3 AND user_id = $4
RETURNING deck_id, user_id, name, description, is_public, status, settings, card_count, cloned_from, created_at, updated_at
`

type UpdateDeckParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	DeckID      uuid.UUID      `json:"deck_id"`
	UserID      uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, updateDeck,
		arg.Name,
		arg.Description,
		arg.DeckID,
		arg.UserID,
	)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CardCount,
		&i.ClonedFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeckSettings = `-- name: UpdateDeckSettings :one
UPDATE decks
SET settings   = $2,
    updated_at = now()
WHERE deck_id = $1
RETURNING deck_id, user_id, name, description, is_public, status, settings, card_count, cloned_from, created_at, updated_at
`

type UpdateDeckSettingsParams struct {
	DeckID   uuid.UUID       `json:"deck_id"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) UpdateDeckSettings(ctx context.Context, arg UpdateDeckSettingsParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, updateDeckSettings, arg.DeckID, arg.Settings)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CardCount,
		&i.ClonedFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeckVisibility = `-- name: UpdateDeckVisibility :one
UPDATE decks
SET is_public  = $1,
    updated_at = now()
WHERE deck_id = $2 AND user_id = $3
RETURNING deck_id, user_id, name, description, is_public, status, settings, card_count, cloned_from, created_at, updated_at
`

type UpdateDeckVisibilityParams struct {
	IsPublic bool      `json:"is_public"`
	DeckID   uuid.UUID `json:"deck_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateDeckVisibility(ctx context.Context, arg UpdateDeckVisibilityParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, updateDeckVisibility, arg.IsPublic, arg.DeckID, arg.UserID)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Status,
		&i.Settings,
		&i.CardCount,
		&i.ClonedFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
