// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: folder_deck.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addDeckToFolder = `-- name: AddDeckToFolder :one
INSERT INTO folder_decks (folder_id, deck_id)
VALUES ($1, $2)
RETURNING folder_id, deck_id, added_at
`

type AddDeckToFolderParams struct {
	FolderID uuid.UUID `json:"folder_id"`
	DeckID   uuid.UUID `json:"deck_id"`
}

func (q *Queries) AddDeckToFolder(ctx context.Context, arg AddDeckToFolderParams) (FolderDeck, error) {
	row := q.db.QueryRowContext(ctx, addDeckToFolder, arg.FolderID, arg.DeckID)
	var i FolderDeck
	err := row.Scan(&i.FolderID, &i.DeckID, &i.AddedAt)
	return i, err
}

const isDeckInFolder = `-- name: IsDeckInFolder :one
SELECT EXISTS(
    SELECT 1 FROM folder_decks WHERE folder_id = $1 AND deck_id = $2
) AS exists
`

type IsDeckInFolderParams struct {
	FolderID uuid.UUID `json:"folder_id"`
	DeckID   uuid.UUID `json:"deck_id"`
}

func (q *Queries) IsDeckInFolder(ctx context.Context, arg IsDeckInFolderParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isDeckInFolder, arg.FolderID, arg.DeckID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDecksByFolder = `-- name: ListDecksByFolder :many
SELECT d.deck_id, d.user_id, d.name, d.description, d.is_public, d.status, d.settings, d.card_count, d.cloned_from, d.created_at, d.updated_at
FROM decks d
JOIN folder_decks fd ON d.deck_id = fd.deck_id
WHERE fd.folder_id = $1 AND d.status != 'deleted'
ORDER BY fd.added_at DESC
`

func (q *Queries) ListDecksByFolder(ctx context.Context, folderID uuid.UUID) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listDecksByFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.DeckID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Status,
			&i.Settings,
			&i.CardCount,
			&i.ClonedFrom,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDeckFromFolder = `-- name: RemoveDeckFromFolder :exec
DELETE FROM folder_decks WHERE folder_id = $1 AND deck_id = $2
`

type RemoveDeckFromFolderParams struct {
	FolderID uuid.UUID `json:"folder_id"`
	DeckID   uuid.UUID `json:"deck_id"`
}

func (q *Queries) RemoveDeckFromFolder(ctx context.Context, arg RemoveDeckFromFolderParams) error {
	_, err := q.db.ExecContext(ctx, removeDeckFromFolder, arg.FolderID, arg.DeckID)
	return err
}
