// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: folder.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (user_id, name, description)
VALUES ($1, $2, $3)
RETURNING folder_id, user_id, name, description, created_at, updated_at
`

type CreateFolderParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, arg.UserID, arg.Name, arg.Description)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE folder_id = $1 AND user_id = $2
`

type DeleteFolderParams struct {
	FolderID uuid.UUID `json:"folder_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, arg.FolderID, arg.UserID)
	return err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT folder_id, user_id, name, description, created_at, updated_at FROM folders WHERE folder_id = $1 LIMIT 1
`

func (q *Queries) GetFolderByID(ctx context.Context, folderID uuid.UUID) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByID, folderID)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoldersByUser = `-- name: ListFoldersByUser :many
SELECT folder_id, user_id, name, description, created_at, updated_at FROM folders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFoldersByUser(ctx context.Context, userID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.FolderID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at  = now()
WHERE folder_id = $3 AND user_id = $4
RETURNING folder_id, user_id, name, description, created_at, updated_at
`

type UpdateFolderParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	FolderID    uuid.UUID      `json:"folder_id"`
	UserID      uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, updateFolder,
		arg.Name,
		arg.Description,
		arg.FolderID,
		arg.UserID,
	)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
