// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type CardLanguage string

const (
	CardLanguageVi       CardLanguage = "vi"
	CardLanguageEn       CardLanguage = "en"
	CardLanguageEs       CardLanguage = "es"
	CardLanguageFr       CardLanguage = "fr"
	CardLanguageIt       CardLanguage = "it"
	CardLanguageDe       CardLanguage = "de"
	CardLanguageRu       CardLanguage = "ru"
	CardLanguageJa       CardLanguage = "ja"
	CardLanguageJaRomaji CardLanguage = "ja_romaji"
	CardLanguageZhHans   CardLanguage = "zh_hans"
	CardLanguageZhHant   CardLanguage = "zh_hant"
	CardLanguageZhPinyin CardLanguage = "zh_pinyin"
	CardLanguageKo       CardLanguage = "ko"
)

func (e *CardLanguage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardLanguage(s)
	case string:
		*e = CardLanguage(s)
	default:
		return fmt.Errorf("unsupported scan type for CardLanguage: %T", src)
	}
	return nil
}

type NullCardLanguage struct {
	CardLanguage CardLanguage `json:"card_language"`
	Valid        bool         `json:"valid"` // Valid is true if CardLanguage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.CardLanguage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardLanguage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardLanguage), nil
}

type ContentStatus string

const (
	ContentStatusActive  ContentStatus = "active"
	ContentStatusHidden  ContentStatus = "hidden"
	ContentStatusDeleted ContentStatus = "deleted"
)

func (e *ContentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentStatus(s)
	case string:
		*e = ContentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentStatus: %T", src)
	}
	return nil
}

type NullContentStatus struct {
	ContentStatus ContentStatus `json:"content_status"`
	Valid         bool          `json:"valid"` // Valid is true if ContentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentStatus), nil
}

type Card struct {
	CardID    uuid.UUID `json:"card_id"`
	UserID    uuid.UUID `json:"user_id"`
	DeckID    uuid.UUID `json:"deck_id"`
	NoteID    uuid.UUID `json:"note_id"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
}

type Deck struct {
	DeckID      uuid.UUID       `json:"deck_id"`
	UserID      uuid.UUID       `json:"user_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	IsPublic    bool            `json:"is_public"`
	Status      string          `json:"status"`
	Settings    json.RawMessage `json:"settings"`
	CardCount   int32           `json:"card_count"`
	ClonedFrom  uuid.NullUUID   `json:"cloned_from"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Folder struct {
	FolderID    uuid.UUID      `json:"folder_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type FolderDeck struct {
	FolderID uuid.UUID `json:"folder_id"`
	DeckID   uuid.UUID `json:"deck_id"`
	AddedAt  time.Time `json:"added_at"`
}

type Note struct {
	NoteID       uuid.UUID      `json:"note_id"`
	UserID       uuid.UUID      `json:"user_id"`
	ContentFront string         `json:"content_front"`
	ContentBack  string         `json:"content_back"`
	ImageUrl     sql.NullString `json:"image_url"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	LangFront    string         `json:"lang_front"`
	LangBack     string         `json:"lang_back"`
}
