// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: note.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, content_front, content_back, image_url)
VALUES ($1, $2, $3, $4)
RETURNING note_id, user_id, content_front, content_back, image_url, created_at, updated_at
`

type CreateNoteParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	ContentFront string         `json:"content_front"`
	ContentBack  string         `json:"content_back"`
	ImageUrl     sql.NullString `json:"image_url"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.UserID,
		arg.ContentFront,
		arg.ContentBack,
		arg.ImageUrl,
	)
	var i Note
	err := row.Scan(
		&i.NoteID,
		&i.UserID,
		&i.ContentFront,
		&i.ContentBack,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE note_id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	NoteID uuid.UUID `json:"note_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteNote, arg.NoteID, arg.UserID)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT note_id, user_id, content_front, content_back, image_url, created_at, updated_at FROM notes WHERE note_id = $1 LIMIT 1
`

func (q *Queries) GetNoteByID(ctx context.Context, noteID uuid.UUID) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, noteID)
	var i Note
	err := row.Scan(
		&i.NoteID,
		&i.UserID,
		&i.ContentFront,
		&i.ContentBack,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET content_front = COALESCE($1, content_front),
    content_back  = COALESCE($2, content_back),
    image_url     = COALESCE($3, image_url),
    updated_at    = now()
WHERE note_id = $4 AND user_id = $5
RETURNING note_id, user_id, content_front, content_back, image_url, created_at, updated_at
`

type UpdateNoteParams struct {
	ContentFront sql.NullString `json:"content_front"`
	ContentBack  sql.NullString `json:"content_back"`
	ImageUrl     sql.NullString `json:"image_url"`
	NoteID       uuid.UUID      `json:"note_id"`
	UserID       uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.ContentFront,
		arg.ContentBack,
		arg.ImageUrl,
		arg.NoteID,
		arg.UserID,
	)
	var i Note
	err := row.Scan(
		&i.NoteID,
		&i.UserID,
		&i.ContentFront,
		&i.ContentBack,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
