// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: study_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StudyService_StartSession_FullMethodName          = "/pb.StudyService/StartSession"
	StudyService_GetSession_FullMethodName            = "/pb.StudyService/GetSession"
	StudyService_ReviewCard_FullMethodName            = "/pb.StudyService/ReviewCard"
	StudyService_FinishSession_FullMethodName         = "/pb.StudyService/FinishSession"
	StudyService_GetDueCards_FullMethodName           = "/pb.StudyService/GetDueCards"
	StudyService_GetRecentSessionCards_FullMethodName = "/pb.StudyService/GetRecentSessionCards"
	StudyService_GetRecentDecks_FullMethodName        = "/pb.StudyService/GetRecentDecks"
	StudyService_GetDeckProgress_FullMethodName       = "/pb.StudyService/GetDeckProgress"
)

// StudyServiceClient is the client API for StudyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudyServiceClient interface {
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	ReviewCard(ctx context.Context, in *ReviewCardRequest, opts ...grpc.CallOption) (*ReviewCardResponse, error)
	FinishSession(ctx context.Context, in *FinishSessionRequest, opts ...grpc.CallOption) (*FinishSessionResponse, error)
	GetDueCards(ctx context.Context, in *GetDueCardsRequest, opts ...grpc.CallOption) (*GetDueCardsResponse, error)
	GetRecentSessionCards(ctx context.Context, in *GetRecentSessionCardsRequest, opts ...grpc.CallOption) (*GetRecentSessionCardsResponse, error)
	GetRecentDecks(ctx context.Context, in *GetRecentDecksRequest, opts ...grpc.CallOption) (*GetRecentDecksResponse, error)
	GetDeckProgress(ctx context.Context, in *GetDeckProgressRequest, opts ...grpc.CallOption) (*DeckProgressResponse, error)
}

type studyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudyServiceClient(cc grpc.ClientConnInterface) StudyServiceClient {
	return &studyServiceClient{cc}
}

func (c *studyServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, StudyService_StartSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, StudyService_GetSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) ReviewCard(ctx context.Context, in *ReviewCardRequest, opts ...grpc.CallOption) (*ReviewCardResponse, error) {
	out := new(ReviewCardResponse)
	err := c.cc.Invoke(ctx, StudyService_ReviewCard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) FinishSession(ctx context.Context, in *FinishSessionRequest, opts ...grpc.CallOption) (*FinishSessionResponse, error) {
	out := new(FinishSessionResponse)
	err := c.cc.Invoke(ctx, StudyService_FinishSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) GetDueCards(ctx context.Context, in *GetDueCardsRequest, opts ...grpc.CallOption) (*GetDueCardsResponse, error) {
	out := new(GetDueCardsResponse)
	err := c.cc.Invoke(ctx, StudyService_GetDueCards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) GetRecentSessionCards(ctx context.Context, in *GetRecentSessionCardsRequest, opts ...grpc.CallOption) (*GetRecentSessionCardsResponse, error) {
	out := new(GetRecentSessionCardsResponse)
	err := c.cc.Invoke(ctx, StudyService_GetRecentSessionCards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) GetRecentDecks(ctx context.Context, in *GetRecentDecksRequest, opts ...grpc.CallOption) (*GetRecentDecksResponse, error) {
	out := new(GetRecentDecksResponse)
	err := c.cc.Invoke(ctx, StudyService_GetRecentDecks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceClient) GetDeckProgress(ctx context.Context, in *GetDeckProgressRequest, opts ...grpc.CallOption) (*DeckProgressResponse, error) {
	out := new(DeckProgressResponse)
	err := c.cc.Invoke(ctx, StudyService_GetDeckProgress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudyServiceServer is the server API for StudyService service.
// All implementations must embed UnimplementedStudyServiceServer
// for forward compatibility
type StudyServiceServer interface {
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	ReviewCard(context.Context, *ReviewCardRequest) (*ReviewCardResponse, error)
	FinishSession(context.Context, *FinishSessionRequest) (*FinishSessionResponse, error)
	GetDueCards(context.Context, *GetDueCardsRequest) (*GetDueCardsResponse, error)
	GetRecentSessionCards(context.Context, *GetRecentSessionCardsRequest) (*GetRecentSessionCardsResponse, error)
	GetRecentDecks(context.Context, *GetRecentDecksRequest) (*GetRecentDecksResponse, error)
	GetDeckProgress(context.Context, *GetDeckProgressRequest) (*DeckProgressResponse, error)
	mustEmbedUnimplementedStudyServiceServer()
}

// UnimplementedStudyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStudyServiceServer struct {
}

func (UnimplementedStudyServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedStudyServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedStudyServiceServer) ReviewCard(context.Context, *ReviewCardRequest) (*ReviewCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewCard not implemented")
}
func (UnimplementedStudyServiceServer) FinishSession(context.Context, *FinishSessionRequest) (*FinishSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishSession not implemented")
}
func (UnimplementedStudyServiceServer) GetDueCards(context.Context, *GetDueCardsRequest) (*GetDueCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDueCards not implemented")
}
func (UnimplementedStudyServiceServer) GetRecentSessionCards(context.Context, *GetRecentSessionCardsRequest) (*GetRecentSessionCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentSessionCards not implemented")
}
func (UnimplementedStudyServiceServer) GetRecentDecks(context.Context, *GetRecentDecksRequest) (*GetRecentDecksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentDecks not implemented")
}
func (UnimplementedStudyServiceServer) GetDeckProgress(context.Context, *GetDeckProgressRequest) (*DeckProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeckProgress not implemented")
}
func (UnimplementedStudyServiceServer) mustEmbedUnimplementedStudyServiceServer() {}

// UnsafeStudyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudyServiceServer will
// result in compilation errors.
type UnsafeStudyServiceServer interface {
	mustEmbedUnimplementedStudyServiceServer()
}

func RegisterStudyServiceServer(s grpc.ServiceRegistrar, srv StudyServiceServer) {
	s.RegisterService(&StudyService_ServiceDesc, srv)
}

func _StudyService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_ReviewCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).ReviewCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_ReviewCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).ReviewCard(ctx, req.(*ReviewCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_FinishSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).FinishSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_FinishSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).FinishSession(ctx, req.(*FinishSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_GetDueCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDueCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).GetDueCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_GetDueCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).GetDueCards(ctx, req.(*GetDueCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_GetRecentSessionCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentSessionCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).GetRecentSessionCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_GetRecentSessionCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).GetRecentSessionCards(ctx, req.(*GetRecentSessionCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_GetRecentDecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentDecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).GetRecentDecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_GetRecentDecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).GetRecentDecks(ctx, req.(*GetRecentDecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyService_GetDeckProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeckProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceServer).GetDeckProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyService_GetDeckProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceServer).GetDeckProgress(ctx, req.(*GetDeckProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudyService_ServiceDesc is the grpc.ServiceDesc for StudyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StudyService",
	HandlerType: (*StudyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _StudyService_StartSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _StudyService_GetSession_Handler,
		},
		{
			MethodName: "ReviewCard",
			Handler:    _StudyService_ReviewCard_Handler,
		},
		{
			MethodName: "FinishSession",
			Handler:    _StudyService_FinishSession_Handler,
		},
		{
			MethodName: "GetDueCards",
			Handler:    _StudyService_GetDueCards_Handler,
		},
		{
			MethodName: "GetRecentSessionCards",
			Handler:    _StudyService_GetRecentSessionCards_Handler,
		},
		{
			MethodName: "GetRecentDecks",
			Handler:    _StudyService_GetRecentDecks_Handler,
		},
		{
			MethodName: "GetDeckProgress",
			Handler:    _StudyService_GetDeckProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "study_service.proto",
}
