// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: fsrs_weights.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deactivateWeights = `-- name: DeactivateWeights :exec
UPDATE user_fsrs_weights SET is_active = FALSE
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) DeactivateWeights(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateWeights, userID)
	return err
}

const getActiveWeights = `-- name: GetActiveWeights :one
SELECT user_id, version, weights, is_active, trained_on_reviews, training_loss, created_at FROM user_fsrs_weights
WHERE user_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveWeights(ctx context.Context, userID uuid.UUID) (UserFsrsWeight, error) {
	row := q.db.QueryRowContext(ctx, getActiveWeights, userID)
	var i UserFsrsWeight
	err := row.Scan(
		&i.UserID,
		&i.Version,
		&i.Weights,
		&i.IsActive,
		&i.TrainedOnReviews,
		&i.TrainingLoss,
		&i.CreatedAt,
	)
	return i, err
}

const getNextWeightVersion = `-- name: GetNextWeightVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM user_fsrs_weights
WHERE user_id = $1
`

func (q *Queries) GetNextWeightVersion(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextWeightVersion, userID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const insertWeights = `-- name: InsertWeights :one
INSERT INTO user_fsrs_weights (user_id, version, weights, is_active, trained_on_reviews, training_loss)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, version, weights, is_active, trained_on_reviews, training_loss, created_at
`

type InsertWeightsParams struct {
	UserID           uuid.UUID       `json:"user_id"`
	Version          int32           `json:"version"`
	Weights          pq.Float64Array `json:"weights"`
	IsActive         bool            `json:"is_active"`
	TrainedOnReviews sql.NullInt32   `json:"trained_on_reviews"`
	TrainingLoss     sql.NullFloat64 `json:"training_loss"`
}

func (q *Queries) InsertWeights(ctx context.Context, arg InsertWeightsParams) (UserFsrsWeight, error) {
	row := q.db.QueryRowContext(ctx, insertWeights,
		arg.UserID,
		arg.Version,
		arg.Weights,
		arg.IsActive,
		arg.TrainedOnReviews,
		arg.TrainingLoss,
	)
	var i UserFsrsWeight
	err := row.Scan(
		&i.UserID,
		&i.Version,
		&i.Weights,
		&i.IsActive,
		&i.TrainedOnReviews,
		&i.TrainingLoss,
		&i.CreatedAt,
	)
	return i, err
}
