// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

type CardState string

const (
	CardStateNew        CardState = "new"
	CardStateLearning   CardState = "learning"
	CardStateReview     CardState = "review"
	CardStateRelearning CardState = "relearning"
)

func (e *CardState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardState(s)
	case string:
		*e = CardState(s)
	default:
		return fmt.Errorf("unsupported scan type for CardState: %T", src)
	}
	return nil
}

type NullCardState struct {
	CardState CardState `json:"card_state"`
	Valid     bool      `json:"valid"` // Valid is true if CardState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardState) Scan(value interface{}) error {
	if value == nil {
		ns.CardState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardState), nil
}

type SessionStatus string

const (
	SessionStatusOngoing   SessionStatus = "ongoing"
	SessionStatusCompleted SessionStatus = "completed"
	SessionStatusAbandoned SessionStatus = "abandoned"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type Revlog struct {
	LogID            uuid.UUID     `json:"log_id"`
	UserID           uuid.UUID     `json:"user_id"`
	CardID           uuid.UUID     `json:"card_id"`
	UserCardID       uuid.UUID     `json:"user_card_id"`
	SessionID        uuid.NullUUID `json:"session_id"`
	Rating           int16         `json:"rating"`
	DurationMs       int32         `json:"duration_ms"`
	StateBefore      string        `json:"state_before"`
	StabilityBefore  float64       `json:"stability_before"`
	DifficultyBefore float64       `json:"difficulty_before"`
	ElapsedDays      int32         `json:"elapsed_days"`
	ScheduledDays    int32         `json:"scheduled_days"`
	StateAfter       string        `json:"state_after"`
	StabilityAfter   float64       `json:"stability_after"`
	DifficultyAfter  float64       `json:"difficulty_after"`
	ReviewTime       time.Time     `json:"review_time"`
}

type SessionCard struct {
	SessionID  uuid.UUID     `json:"session_id"`
	Position   int32         `json:"position"`
	CardID     uuid.UUID     `json:"card_id"`
	UserCardID uuid.UUID     `json:"user_card_id"`
	ReviewedAt sql.NullTime  `json:"reviewed_at"`
	Rating     sql.NullInt32 `json:"rating"`
}

type StudySession struct {
	SessionID          uuid.UUID    `json:"session_id"`
	UserID             uuid.UUID    `json:"user_id"`
	DeckID             uuid.UUID    `json:"deck_id"`
	Status             string       `json:"status"`
	TotalCards         int32        `json:"total_cards"`
	CompletedCards     int32        `json:"completed_cards"`
	LastCompletedIndex int32        `json:"last_completed_index"`
	StartedAt          time.Time    `json:"started_at"`
	FinishedAt         sql.NullTime `json:"finished_at"`
	LastAccessedAt     time.Time    `json:"last_accessed_at"`
}

type UserCard struct {
	UserCardID     uuid.UUID    `json:"user_card_id"`
	UserID         uuid.UUID    `json:"user_id"`
	CardID         uuid.UUID    `json:"card_id"`
	DeckID         uuid.UUID    `json:"deck_id"`
	State          string       `json:"state"`
	Stability      float64      `json:"stability"`
	Difficulty     float64      `json:"difficulty"`
	Reps           int32        `json:"reps"`
	Lapses         int32        `json:"lapses"`
	ScheduledDays  int32        `json:"scheduled_days"`
	TAvg           float64      `json:"t_avg"`
	NextReviewDate time.Time    `json:"next_review_date"`
	LastReviewDate sql.NullTime `json:"last_review_date"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type UserFsrsWeight struct {
	UserID           uuid.UUID       `json:"user_id"`
	Version          int32           `json:"version"`
	Weights          pq.Float64Array `json:"weights"`
	IsActive         bool            `json:"is_active"`
	TrainedOnReviews sql.NullInt32   `json:"trained_on_reviews"`
	TrainingLoss     sql.NullFloat64 `json:"training_loss"`
	CreatedAt        time.Time       `json:"created_at"`
}
