// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: revlog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertRevlog = `-- name: InsertRevlog :one
INSERT INTO revlogs (
    user_id, card_id, user_card_id, session_id,
    rating, duration_ms,
    state_before, stability_before, difficulty_before,
    elapsed_days, scheduled_days,
    state_after, stability_after, difficulty_after
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING log_id, user_id, card_id, user_card_id, session_id, rating, duration_ms, state_before, stability_before, difficulty_before, elapsed_days, scheduled_days, state_after, stability_after, difficulty_after, review_time
`

type InsertRevlogParams struct {
	UserID           uuid.UUID     `json:"user_id"`
	CardID           uuid.UUID     `json:"card_id"`
	UserCardID       uuid.UUID     `json:"user_card_id"`
	SessionID        uuid.NullUUID `json:"session_id"`
	Rating           int16         `json:"rating"`
	DurationMs       int32         `json:"duration_ms"`
	StateBefore      string        `json:"state_before"`
	StabilityBefore  float64       `json:"stability_before"`
	DifficultyBefore float64       `json:"difficulty_before"`
	ElapsedDays      int32         `json:"elapsed_days"`
	ScheduledDays    int32         `json:"scheduled_days"`
	StateAfter       string        `json:"state_after"`
	StabilityAfter   float64       `json:"stability_after"`
	DifficultyAfter  float64       `json:"difficulty_after"`
}

func (q *Queries) InsertRevlog(ctx context.Context, arg InsertRevlogParams) (Revlog, error) {
	row := q.db.QueryRowContext(ctx, insertRevlog,
		arg.UserID,
		arg.CardID,
		arg.UserCardID,
		arg.SessionID,
		arg.Rating,
		arg.DurationMs,
		arg.StateBefore,
		arg.StabilityBefore,
		arg.DifficultyBefore,
		arg.ElapsedDays,
		arg.ScheduledDays,
		arg.StateAfter,
		arg.StabilityAfter,
		arg.DifficultyAfter,
	)
	var i Revlog
	err := row.Scan(
		&i.LogID,
		&i.UserID,
		&i.CardID,
		&i.UserCardID,
		&i.SessionID,
		&i.Rating,
		&i.DurationMs,
		&i.StateBefore,
		&i.StabilityBefore,
		&i.DifficultyBefore,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.StateAfter,
		&i.StabilityAfter,
		&i.DifficultyAfter,
		&i.ReviewTime,
	)
	return i, err
}

const listRevlogsByUserCard = `-- name: ListRevlogsByUserCard :many
SELECT log_id, user_id, card_id, user_card_id, session_id, rating, duration_ms, state_before, stability_before, difficulty_before, elapsed_days, scheduled_days, state_after, stability_after, difficulty_after, review_time FROM revlogs
WHERE user_card_id = $1
ORDER BY review_time DESC
LIMIT $2
`

type ListRevlogsByUserCardParams struct {
	UserCardID uuid.UUID `json:"user_card_id"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListRevlogsByUserCard(ctx context.Context, arg ListRevlogsByUserCardParams) ([]Revlog, error) {
	rows, err := q.db.QueryContext(ctx, listRevlogsByUserCard, arg.UserCardID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Revlog{}
	for rows.Next() {
		var i Revlog
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.CardID,
			&i.UserCardID,
			&i.SessionID,
			&i.Rating,
			&i.DurationMs,
			&i.StateBefore,
			&i.StabilityBefore,
			&i.DifficultyBefore,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.StateAfter,
			&i.StabilityAfter,
			&i.DifficultyAfter,
			&i.ReviewTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
