// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: session_card.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getSessionCardByCard = `-- name: GetSessionCardByCard :one
SELECT session_id, position, card_id, user_card_id, reviewed_at, rating FROM session_cards
WHERE session_id = $1 AND card_id = $2
`

type GetSessionCardByCardParams struct {
	SessionID uuid.UUID `json:"session_id"`
	CardID    uuid.UUID `json:"card_id"`
}

func (q *Queries) GetSessionCardByCard(ctx context.Context, arg GetSessionCardByCardParams) (SessionCard, error) {
	row := q.db.QueryRowContext(ctx, getSessionCardByCard, arg.SessionID, arg.CardID)
	var i SessionCard
	err := row.Scan(
		&i.SessionID,
		&i.Position,
		&i.CardID,
		&i.UserCardID,
		&i.ReviewedAt,
		&i.Rating,
	)
	return i, err
}

const insertSessionCard = `-- name: InsertSessionCard :one
INSERT INTO session_cards (session_id, position, card_id, user_card_id)
VALUES ($1, $2, $3, $4)
RETURNING session_id, position, card_id, user_card_id, reviewed_at, rating
`

type InsertSessionCardParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	Position   int32     `json:"position"`
	CardID     uuid.UUID `json:"card_id"`
	UserCardID uuid.UUID `json:"user_card_id"`
}

func (q *Queries) InsertSessionCard(ctx context.Context, arg InsertSessionCardParams) (SessionCard, error) {
	row := q.db.QueryRowContext(ctx, insertSessionCard,
		arg.SessionID,
		arg.Position,
		arg.CardID,
		arg.UserCardID,
	)
	var i SessionCard
	err := row.Scan(
		&i.SessionID,
		&i.Position,
		&i.CardID,
		&i.UserCardID,
		&i.ReviewedAt,
		&i.Rating,
	)
	return i, err
}

const listSessionCards = `-- name: ListSessionCards :many
SELECT session_id, position, card_id, user_card_id, reviewed_at, rating FROM session_cards
WHERE session_id = $1
ORDER BY position
`

func (q *Queries) ListSessionCards(ctx context.Context, sessionID uuid.UUID) ([]SessionCard, error) {
	rows, err := q.db.QueryContext(ctx, listSessionCards, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionCard{}
	for rows.Next() {
		var i SessionCard
		if err := rows.Scan(
			&i.SessionID,
			&i.Position,
			&i.CardID,
			&i.UserCardID,
			&i.ReviewedAt,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionCardReviewed = `-- name: MarkSessionCardReviewed :one
UPDATE session_cards SET
    reviewed_at = NOW(),
    rating      = $3
WHERE session_id = $1 AND card_id = $2
RETURNING session_id, position, card_id, user_card_id, reviewed_at, rating
`

type MarkSessionCardReviewedParams struct {
	SessionID uuid.UUID     `json:"session_id"`
	CardID    uuid.UUID     `json:"card_id"`
	Rating    sql.NullInt32 `json:"rating"`
}

func (q *Queries) MarkSessionCardReviewed(ctx context.Context, arg MarkSessionCardReviewedParams) (SessionCard, error) {
	row := q.db.QueryRowContext(ctx, markSessionCardReviewed, arg.SessionID, arg.CardID, arg.Rating)
	var i SessionCard
	err := row.Scan(
		&i.SessionID,
		&i.Position,
		&i.CardID,
		&i.UserCardID,
		&i.ReviewedAt,
		&i.Rating,
	)
	return i, err
}
