// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: study_session.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const abandonStudySession = `-- name: AbandonStudySession :one
UPDATE study_sessions SET
    status           = 'abandoned',
    finished_at      = NOW(),
    last_accessed_at = NOW()
WHERE session_id = $1
RETURNING session_id, user_id, deck_id, status, total_cards, completed_cards, last_completed_index, started_at, finished_at, last_accessed_at
`

func (q *Queries) AbandonStudySession(ctx context.Context, sessionID uuid.UUID) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, abandonStudySession, sessionID)
	var i StudySession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.DeckID,
		&i.Status,
		&i.TotalCards,
		&i.CompletedCards,
		&i.LastCompletedIndex,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const createStudySession = `-- name: CreateStudySession :one
INSERT INTO study_sessions (user_id, deck_id, total_cards)
VALUES ($1, $2, $3)
RETURNING session_id, user_id, deck_id, status, total_cards, completed_cards, last_completed_index, started_at, finished_at, last_accessed_at
`

type CreateStudySessionParams struct {
	UserID     uuid.UUID `json:"user_id"`
	DeckID     uuid.UUID `json:"deck_id"`
	TotalCards int32     `json:"total_cards"`
}

func (q *Queries) CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, createStudySession, arg.UserID, arg.DeckID, arg.TotalCards)
	var i StudySession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.DeckID,
		&i.Status,
		&i.TotalCards,
		&i.CompletedCards,
		&i.LastCompletedIndex,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const finishStudySession = `-- name: FinishStudySession :one
UPDATE study_sessions SET
    status           = 'completed',
    finished_at      = NOW(),
    last_accessed_at = NOW()
WHERE session_id = $1
RETURNING session_id, user_id, deck_id, status, total_cards, completed_cards, last_completed_index, started_at, finished_at, last_accessed_at
`

func (q *Queries) FinishStudySession(ctx context.Context, sessionID uuid.UUID) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, finishStudySession, sessionID)
	var i StudySession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.DeckID,
		&i.Status,
		&i.TotalCards,
		&i.CompletedCards,
		&i.LastCompletedIndex,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getOngoingSessionByDeck = `-- name: GetOngoingSessionByDeck :one
SELECT session_id, user_id, deck_id, status, total_cards, completed_cards, last_completed_index, started_at, finished_at, last_accessed_at FROM study_sessions
WHERE user_id = $1 AND deck_id = $2 AND status = 'ongoing'
LIMIT 1
`

type GetOngoingSessionByDeckParams struct {
	UserID uuid.UUID `json:"user_id"`
	DeckID uuid.UUID `json:"deck_id"`
}

func (q *Queries) GetOngoingSessionByDeck(ctx context.Context, arg GetOngoingSessionByDeckParams) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, getOngoingSessionByDeck, arg.UserID, arg.DeckID)
	var i StudySession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.DeckID,
		&i.Status,
		&i.TotalCards,
		&i.CompletedCards,
		&i.LastCompletedIndex,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getStudySession = `-- name: GetStudySession :one
SELECT session_id, user_id, deck_id, status, total_cards, completed_cards, last_completed_index, started_at, finished_at, last_accessed_at FROM study_sessions WHERE session_id = $1
`

func (q *Queries) GetStudySession(ctx context.Context, sessionID uuid.UUID) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, getStudySession, sessionID)
	var i StudySession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.DeckID,
		&i.Status,
		&i.TotalCards,
		&i.CompletedCards,
		&i.LastCompletedIndex,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const incrementCompletedCards = `-- name: IncrementCompletedCards :one
UPDATE study_sessions SET
    completed_cards      = completed_cards + 1,
    last_completed_index = last_completed_index + 1,
    last_accessed_at     = NOW()
WHERE session_id = $1
RETURNING session_id, user_id, deck_id, status, total_cards, completed_cards, last_completed_index, started_at, finished_at, last_accessed_at
`

func (q *Queries) IncrementCompletedCards(ctx context.Context, sessionID uuid.UUID) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, incrementCompletedCards, sessionID)
	var i StudySession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.DeckID,
		&i.Status,
		&i.TotalCards,
		&i.CompletedCards,
		&i.LastCompletedIndex,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastAccessedAt,
	)
	return i, err
}
