// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_card.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getUserCardByID = `-- name: GetUserCardByID :one
SELECT user_card_id, user_id, card_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, t_avg, next_review_date, last_review_date, created_at, updated_at FROM user_cards WHERE user_card_id = $1
`

func (q *Queries) GetUserCardByID(ctx context.Context, userCardID uuid.UUID) (UserCard, error) {
	row := q.db.QueryRowContext(ctx, getUserCardByID, userCardID)
	var i UserCard
	err := row.Scan(
		&i.UserCardID,
		&i.UserID,
		&i.CardID,
		&i.DeckID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.ScheduledDays,
		&i.TAvg,
		&i.NextReviewDate,
		&i.LastReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCardByUserAndCard = `-- name: GetUserCardByUserAndCard :one
SELECT user_card_id, user_id, card_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, t_avg, next_review_date, last_review_date, created_at, updated_at FROM user_cards WHERE user_id = $1 AND card_id = $2
`

type GetUserCardByUserAndCardParams struct {
	UserID uuid.UUID `json:"user_id"`
	CardID uuid.UUID `json:"card_id"`
}

func (q *Queries) GetUserCardByUserAndCard(ctx context.Context, arg GetUserCardByUserAndCardParams) (UserCard, error) {
	row := q.db.QueryRowContext(ctx, getUserCardByUserAndCard, arg.UserID, arg.CardID)
	var i UserCard
	err := row.Scan(
		&i.UserCardID,
		&i.UserID,
		&i.CardID,
		&i.DeckID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.ScheduledDays,
		&i.TAvg,
		&i.NextReviewDate,
		&i.LastReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueUserCards = `-- name: ListDueUserCards :many
SELECT user_card_id, user_id, card_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, t_avg, next_review_date, last_review_date, created_at, updated_at FROM user_cards
WHERE user_id = $1
  AND state != 'new'
  AND next_review_date <= NOW()
ORDER BY next_review_date
LIMIT $2
`

type ListDueUserCardsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListDueUserCards(ctx context.Context, arg ListDueUserCardsParams) ([]UserCard, error) {
	rows, err := q.db.QueryContext(ctx, listDueUserCards, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserCard{}
	for rows.Next() {
		var i UserCard
		if err := rows.Scan(
			&i.UserCardID,
			&i.UserID,
			&i.CardID,
			&i.DeckID,
			&i.State,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.ScheduledDays,
			&i.TAvg,
			&i.NextReviewDate,
			&i.LastReviewDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueUserCardsByDeck = `-- name: ListDueUserCardsByDeck :many
SELECT user_card_id, user_id, card_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, t_avg, next_review_date, last_review_date, created_at, updated_at FROM user_cards
WHERE user_id = $1
  AND deck_id = $2
  AND state != 'new'
  AND next_review_date <= NOW()
ORDER BY next_review_date
LIMIT $3
`

type ListDueUserCardsByDeckParams struct {
	UserID uuid.UUID `json:"user_id"`
	DeckID uuid.UUID `json:"deck_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListDueUserCardsByDeck(ctx context.Context, arg ListDueUserCardsByDeckParams) ([]UserCard, error) {
	rows, err := q.db.QueryContext(ctx, listDueUserCardsByDeck, arg.UserID, arg.DeckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserCard{}
	for rows.Next() {
		var i UserCard
		if err := rows.Scan(
			&i.UserCardID,
			&i.UserID,
			&i.CardID,
			&i.DeckID,
			&i.State,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.ScheduledDays,
			&i.TAvg,
			&i.NextReviewDate,
			&i.LastReviewDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewUserCardsByDeck = `-- name: ListNewUserCardsByDeck :many
SELECT user_card_id, user_id, card_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, t_avg, next_review_date, last_review_date, created_at, updated_at FROM user_cards
WHERE user_id = $1
  AND deck_id = $2
  AND state = 'new'
ORDER BY created_at
LIMIT $3
`

type ListNewUserCardsByDeckParams struct {
	UserID uuid.UUID `json:"user_id"`
	DeckID uuid.UUID `json:"deck_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListNewUserCardsByDeck(ctx context.Context, arg ListNewUserCardsByDeckParams) ([]UserCard, error) {
	rows, err := q.db.QueryContext(ctx, listNewUserCardsByDeck, arg.UserID, arg.DeckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserCard{}
	for rows.Next() {
		var i UserCard
		if err := rows.Scan(
			&i.UserCardID,
			&i.UserID,
			&i.CardID,
			&i.DeckID,
			&i.State,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.ScheduledDays,
			&i.TAvg,
			&i.NextReviewDate,
			&i.LastReviewDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserCardFSRS = `-- name: UpdateUserCardFSRS :one
UPDATE user_cards SET
    state            = $2,
    stability        = $3,
    difficulty       = $4,
    reps             = $5,
    lapses           = $6,
    scheduled_days   = $7,
    next_review_date = $8,
    last_review_date = $9,
    updated_at       = CURRENT_TIMESTAMP
WHERE user_card_id = $1
RETURNING user_card_id, user_id, card_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, t_avg, next_review_date, last_review_date, created_at, updated_at
`

type UpdateUserCardFSRSParams struct {
	UserCardID     uuid.UUID    `json:"user_card_id"`
	State          string       `json:"state"`
	Stability      float64      `json:"stability"`
	Difficulty     float64      `json:"difficulty"`
	Reps           int32        `json:"reps"`
	Lapses         int32        `json:"lapses"`
	ScheduledDays  int32        `json:"scheduled_days"`
	NextReviewDate time.Time    `json:"next_review_date"`
	LastReviewDate sql.NullTime `json:"last_review_date"`
}

func (q *Queries) UpdateUserCardFSRS(ctx context.Context, arg UpdateUserCardFSRSParams) (UserCard, error) {
	row := q.db.QueryRowContext(ctx, updateUserCardFSRS,
		arg.UserCardID,
		arg.State,
		arg.Stability,
		arg.Difficulty,
		arg.Reps,
		arg.Lapses,
		arg.ScheduledDays,
		arg.NextReviewDate,
		arg.LastReviewDate,
	)
	var i UserCard
	err := row.Scan(
		&i.UserCardID,
		&i.UserID,
		&i.CardID,
		&i.DeckID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.ScheduledDays,
		&i.TAvg,
		&i.NextReviewDate,
		&i.LastReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserCard = `-- name: UpsertUserCard :one
INSERT INTO user_cards (user_id, card_id, deck_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, card_id) DO UPDATE
    SET updated_at = CURRENT_TIMESTAMP
RETURNING user_card_id, user_id, card_id, deck_id, state, stability, difficulty, reps, lapses, scheduled_days, t_avg, next_review_date, last_review_date, created_at, updated_at
`

type UpsertUserCardParams struct {
	UserID uuid.UUID `json:"user_id"`
	CardID uuid.UUID `json:"card_id"`
	DeckID uuid.UUID `json:"deck_id"`
}

func (q *Queries) UpsertUserCard(ctx context.Context, arg UpsertUserCardParams) (UserCard, error) {
	row := q.db.QueryRowContext(ctx, upsertUserCard, arg.UserID, arg.CardID, arg.DeckID)
	var i UserCard
	err := row.Scan(
		&i.UserCardID,
		&i.UserID,
		&i.CardID,
		&i.DeckID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.ScheduledDays,
		&i.TAvg,
		&i.NextReviewDate,
		&i.LastReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
