// Code generated by MockGen. DO NOT EDIT.
// Source: mem_pan/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	sqlc "mem_pan/db/sqlc"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddDeckToFolder mocks base method.
func (m *MockStore) AddDeckToFolder(arg0 context.Context, arg1 sqlc.AddDeckToFolderParams) (sqlc.FolderDeck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeckToFolder", arg0, arg1)
	ret0, _ := ret[0].(sqlc.FolderDeck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDeckToFolder indicates an expected call of AddDeckToFolder.
func (mr *MockStoreMockRecorder) AddDeckToFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeckToFolder", reflect.TypeOf((*MockStore)(nil).AddDeckToFolder), arg0, arg1)
}

// CreateCard mocks base method.
func (m *MockStore) CreateCard(arg0 context.Context, arg1 sqlc.CreateCardParams) (sqlc.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCard", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCard indicates an expected call of CreateCard.
func (mr *MockStoreMockRecorder) CreateCard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCard", reflect.TypeOf((*MockStore)(nil).CreateCard), arg0, arg1)
}

// CreateDeck mocks base method.
func (m *MockStore) CreateDeck(arg0 context.Context, arg1 sqlc.CreateDeckParams) (sqlc.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeck", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeck indicates an expected call of CreateDeck.
func (mr *MockStoreMockRecorder) CreateDeck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeck", reflect.TypeOf((*MockStore)(nil).CreateDeck), arg0, arg1)
}

// CreateFolder mocks base method.
func (m *MockStore) CreateFolder(arg0 context.Context, arg1 sqlc.CreateFolderParams) (sqlc.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFolder", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFolder indicates an expected call of CreateFolder.
func (mr *MockStoreMockRecorder) CreateFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFolder", reflect.TypeOf((*MockStore)(nil).CreateFolder), arg0, arg1)
}

// CreateNote mocks base method.
func (m *MockStore) CreateNote(arg0 context.Context, arg1 sqlc.CreateNoteParams) (sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockStoreMockRecorder) CreateNote(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockStore)(nil).CreateNote), arg0, arg1)
}

// CreateRevlog mocks base method.
func (m *MockStore) CreateRevlog(arg0 context.Context, arg1 sqlc.CreateRevlogParams) (sqlc.Revlog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRevlog", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Revlog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRevlog indicates an expected call of CreateRevlog.
func (mr *MockStoreMockRecorder) CreateRevlog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRevlog", reflect.TypeOf((*MockStore)(nil).CreateRevlog), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 sqlc.CreateUserParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// DeleteDeck mocks base method.
func (m *MockStore) DeleteDeck(arg0 context.Context, arg1 uuid.UUID) (sqlc.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeck", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDeck indicates an expected call of DeleteDeck.
func (mr *MockStoreMockRecorder) DeleteDeck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeck", reflect.TypeOf((*MockStore)(nil).DeleteDeck), arg0, arg1)
}

// GetCard mocks base method.
func (m *MockStore) GetCard(arg0 context.Context, arg1 uuid.UUID) (sqlc.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCard", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCard indicates an expected call of GetCard.
func (mr *MockStoreMockRecorder) GetCard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCard", reflect.TypeOf((*MockStore)(nil).GetCard), arg0, arg1)
}

// GetDeck mocks base method.
func (m *MockStore) GetDeck(arg0 context.Context, arg1 uuid.UUID) (sqlc.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeck", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeck indicates an expected call of GetDeck.
func (mr *MockStoreMockRecorder) GetDeck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeck", reflect.TypeOf((*MockStore)(nil).GetDeck), arg0, arg1)
}

// GetFolder mocks base method.
func (m *MockStore) GetFolder(arg0 context.Context, arg1 uuid.UUID) (sqlc.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolder", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolder indicates an expected call of GetFolder.
func (mr *MockStoreMockRecorder) GetFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolder", reflect.TypeOf((*MockStore)(nil).GetFolder), arg0, arg1)
}

// GetNote mocks base method.
func (m *MockStore) GetNote(arg0 context.Context, arg1 uuid.UUID) (sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockStoreMockRecorder) GetNote(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockStore)(nil).GetNote), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockStore) GetUserByID(arg0 context.Context, arg1 uuid.UUID) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreMockRecorder) GetUserByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore)(nil).GetUserByID), arg0, arg1)
}

// ListCardsByDeck mocks base method.
func (m *MockStore) ListCardsByDeck(arg0 context.Context, arg1 uuid.UUID) ([]sqlc.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCardsByDeck", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCardsByDeck indicates an expected call of ListCardsByDeck.
func (mr *MockStoreMockRecorder) ListCardsByDeck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCardsByDeck", reflect.TypeOf((*MockStore)(nil).ListCardsByDeck), arg0, arg1)
}

// ListDecksInFolder mocks base method.
func (m *MockStore) ListDecksInFolder(arg0 context.Context, arg1 uuid.UUID) ([]sqlc.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDecksInFolder", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDecksInFolder indicates an expected call of ListDecksInFolder.
func (mr *MockStoreMockRecorder) ListDecksInFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDecksInFolder", reflect.TypeOf((*MockStore)(nil).ListDecksInFolder), arg0, arg1)
}

// ListDueCardsByDeck mocks base method.
func (m *MockStore) ListDueCardsByDeck(arg0 context.Context, arg1 sqlc.ListDueCardsByDeckParams) ([]sqlc.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDueCardsByDeck", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDueCardsByDeck indicates an expected call of ListDueCardsByDeck.
func (mr *MockStoreMockRecorder) ListDueCardsByDeck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDueCardsByDeck", reflect.TypeOf((*MockStore)(nil).ListDueCardsByDeck), arg0, arg1)
}

// ListFoldersByUser mocks base method.
func (m *MockStore) ListFoldersByUser(arg0 context.Context, arg1 sqlc.ListFoldersByUserParams) ([]sqlc.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFoldersByUser", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFoldersByUser indicates an expected call of ListFoldersByUser.
func (mr *MockStoreMockRecorder) ListFoldersByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFoldersByUser", reflect.TypeOf((*MockStore)(nil).ListFoldersByUser), arg0, arg1)
}

// ListPublicActiveDecks mocks base method.
func (m *MockStore) ListPublicActiveDecks(arg0 context.Context, arg1 sqlc.ListPublicActiveDecksParams) ([]sqlc.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicActiveDecks", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicActiveDecks indicates an expected call of ListPublicActiveDecks.
func (mr *MockStoreMockRecorder) ListPublicActiveDecks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicActiveDecks", reflect.TypeOf((*MockStore)(nil).ListPublicActiveDecks), arg0, arg1)
}

// ListRevlogsByCard mocks base method.
func (m *MockStore) ListRevlogsByCard(arg0 context.Context, arg1 sqlc.ListRevlogsByCardParams) ([]sqlc.Revlog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRevlogsByCard", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Revlog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRevlogsByCard indicates an expected call of ListRevlogsByCard.
func (mr *MockStoreMockRecorder) ListRevlogsByCard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRevlogsByCard", reflect.TypeOf((*MockStore)(nil).ListRevlogsByCard), arg0, arg1)
}

// ListRevlogsByUser mocks base method.
func (m *MockStore) ListRevlogsByUser(arg0 context.Context, arg1 sqlc.ListRevlogsByUserParams) ([]sqlc.Revlog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRevlogsByUser", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Revlog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRevlogsByUser indicates an expected call of ListRevlogsByUser.
func (mr *MockStoreMockRecorder) ListRevlogsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRevlogsByUser", reflect.TypeOf((*MockStore)(nil).ListRevlogsByUser), arg0, arg1)
}

// ListUserDecks mocks base method.
func (m *MockStore) ListUserDecks(arg0 context.Context, arg1 sqlc.ListUserDecksParams) ([]sqlc.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserDecks", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserDecks indicates an expected call of ListUserDecks.
func (mr *MockStoreMockRecorder) ListUserDecks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserDecks", reflect.TypeOf((*MockStore)(nil).ListUserDecks), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(arg0 context.Context, arg1 sqlc.ListUsersParams) ([]sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), arg0, arg1)
}

// RemoveDeckFromFolder mocks base method.
func (m *MockStore) RemoveDeckFromFolder(arg0 context.Context, arg1 sqlc.RemoveDeckFromFolderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDeckFromFolder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDeckFromFolder indicates an expected call of RemoveDeckFromFolder.
func (mr *MockStoreMockRecorder) RemoveDeckFromFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDeckFromFolder", reflect.TypeOf((*MockStore)(nil).RemoveDeckFromFolder), arg0, arg1)
}

// SearchPublicDecks mocks base method.
func (m *MockStore) SearchPublicDecks(arg0 context.Context, arg1 sqlc.SearchPublicDecksParams) ([]sqlc.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPublicDecks", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPublicDecks indicates an expected call of SearchPublicDecks.
func (mr *MockStoreMockRecorder) SearchPublicDecks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPublicDecks", reflect.TypeOf((*MockStore)(nil).SearchPublicDecks), arg0, arg1)
}

// UpdateCardReviewState mocks base method.
func (m *MockStore) UpdateCardReviewState(arg0 context.Context, arg1 sqlc.UpdateCardReviewStateParams) (sqlc.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCardReviewState", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCardReviewState indicates an expected call of UpdateCardReviewState.
func (mr *MockStoreMockRecorder) UpdateCardReviewState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCardReviewState", reflect.TypeOf((*MockStore)(nil).UpdateCardReviewState), arg0, arg1)
}

// UpdateDeck mocks base method.
func (m *MockStore) UpdateDeck(arg0 context.Context, arg1 sqlc.UpdateDeckParams) (sqlc.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeck", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeck indicates an expected call of UpdateDeck.
func (mr *MockStoreMockRecorder) UpdateDeck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeck", reflect.TypeOf((*MockStore)(nil).UpdateDeck), arg0, arg1)
}

// UpdateUserProfile mocks base method.
func (m *MockStore) UpdateUserProfile(arg0 context.Context, arg1 sqlc.UpdateUserProfileParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", arg0, arg1)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockStoreMockRecorder) UpdateUserProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockStore)(nil).UpdateUserProfile), arg0, arg1)
}
